### ISSUE TITLE
[SUGGESTION] More default cross-compat

### ISSUE THREAD

**Issue by Sunconure11** [lukebemish/excavated_variants#1]
There are quite a few mods that add new ores and stone variants. Here are a few I can think of:

https://www.curseforge.com/minecraft/mc-mods/unearthed-both
https://www.curseforge.com/minecraft/mc-mods/promenade
Pretty much most of the material mods supported by this mod: https://www.curseforge.com/minecraft/mc-mods/harvest-scythes
https://www.curseforge.com/minecraft/mc-mods/architects-palette-fabric
https://www.curseforge.com/minecraft/mc-mods/fabric-chisel
https://www.curseforge.com/minecraft/mc-mods/consistency
https://www.curseforge.com/minecraft/mc-mods/twigs

**Comment by lukebemish** [comment]
This is definitely something planned for the future, I will try to add a few more to each update.

**Comment by TheButterbrotMan** [comment]
Unearthed would be awesome!

**Comment by TheButterbrotMan** [comment]
I would like to add this also as suggestion:
https://www.curseforge.com/minecraft/mc-mods/dense-ores-refabricated

**Comment by lukebemish** [comment]
Promenade, Twigs, and Unearthed compatibility was added in the newest version. I will slowly add more compatibility to the default configs as I add feature updates; you can always add compatibility for mods I don't add it for yourself using the configs. The format is fairly simple.

**Comment by lukebemish** [comment]
I have, at this point, added compatibility for most of the mods listed in the original issue, so I am going to close the issue. If you would like specific compatibility for a specific mod, please open a new issue.
