### ISSUE TITLE
[BUG-FORGE] Ores don't drop XP

### ISSUE THREAD

**Issue by Jayx20** [lukebemish/excavated_variants#10]
Hi,

It looks like if I mine ores like coal that have generated inside of another block, it doesn't drop any XP.

I'm on the forge version for 1.18

**Comment by lukebemish** [comment]
Forge-only issue, unfortunately. Forge is screwing with the block break methods, as usual... This will be fixed, but is low-priority as it will be a pain.

**Comment by lukebemish** [comment]
And, nevermind, should be fixed on the next version. Forge is painful at times.
