### ISSUE TITLE
[BUG] mismatched ore variant list when trying to connect to a server

### ISSUE THREAD

**Issue by kuba26038** [lukebemish/excavated_variants#100]
### What went wrong?

it's probably something i have done, but i tried a lot of things and none worked- both the server and the client have the same mod versions and config files and the mod data folder was regenerated a lot of times. so, what do i do in this situation?

### Platform

Forge

### Version

excavated_variants-forge-1.19.2-1.0.3

**Comment by lukebemish** [comment]
Please provide logs, and the contents of the globalresources folder. Additionally - when you regenerate configs, did you delete the globalresources folder? You have to.

**Comment by kuba26038** [comment]
just tried deleting the config and the globalresources folder on both ends and it's still the same.
https://pastebin.com/Jc5JazHr

**Comment by lukebemish** [comment]
Best I can tell no variants are being loaded on the client. What is in the globalresources folder on the client now?

**Comment by kuba26038** [comment]
empty

**Comment by lukebemish** [comment]
Delete the excavated variants config, restart the game

**Comment by kuba26038** [comment]
i knew i was an absolute idiot, thanks a bunch
