### ISSUE TITLE
[ENHANCEMENT] Change name of items using a resource pack.

### ISSUE THREAD

**Issue by TyrionReyukra** [lukebemish/excavated_variants#101]
### What feature would improve this mod?

I'm using the "Create Style Modded Compats" resource pack which renames the Limestone from Quark to "Peridotite" to avoid overlap with the Limestone from Create. Quark limestone ores is still named "Limestone" and not "Peridotite".

Here is what I added inside a copy of the language file of Excavated Variants, all in a resource pack file structure:

{
  "itemGroup.excavated_variants.excavated_variants": "Excavated Variants",
  **_"block.excavated_variants.quark_limestone_coal_ore": "Peridotite Coal Ore"_**
}

### Why would this feature be useful?

Adding consistency for resource packs that change the name of blocks.

### Mod Compatibility

- [x] This feature cannot be added through the config

**Comment by lukebemish** [comment]
You need to change the stone lang value through the config resources which should be in the globalresources folder if you're on 1.19, or in the config folder otherwise
