### ISSUE TITLE
[BUG] Issue with mod in game

### ISSUE THREAD

**Issue by TheRealKalmeira** [lukebemish/excavated_variants#102]
### What went wrong?

I had been using this mod for a while without issue, but when I reset my computer and reinstalled it, the mod shows up in the mod list, but it doesn't work in game. There are no new ores in the creative menu or jei and they all disappeared from my old world. Furthermore, they similarly do not exist in a new test world.

### Platform

Forge

### Version

1.19.2-1.0.3

**Comment by lukebemish** [comment]
Have you tried deleting both the excavated variants config and the globalresources folder?

**Comment by lukebemish** [comment]
If so, please provide a log

**Comment by TheRealKalmeira** [comment]
Deleting the configs worked, thank you.
