### ISSUE TITLE
Double block of deepslate with the ores of oreganized mod

### ISSUE THREAD

**Issue by danijarquee** [lukebemish/excavated_variants#106]
### What went wrong?

 Hi, I have installed the Oreganized mod, this mod adds the two base blocks of stone and deepslate of the ores.
But the Excavated Variants adds another deepslate ore.

### Platform

Forge

### Version

1.19.2

**Comment by lukebemish** [comment]
Are you on 1.18.2 or 1.19.2? I can't seem to find the oreganized mod for 1.19.2. Regardless, I'll update the default config with the most recent stuff I can find for 1.18.2
