### ISSUE TITLE
[ENHANCEMENT] Force generation of overworld ores in nether and vice versa 

### ISSUE THREAD

**Issue by Bazyliii** [lukebemish/excavated_variants#11]
Like in the title, it would be great if we could just use your mod to spawn, for example quartz in overworld, or iron in nether in netherrack form. Dont forget about end dimension

**Comment by lukebemish** [comment]
This would be... _very_ difficult to do. It's basically a whole second mod, and entirely out of the scope of this mod. It's worth pointing out that _Excavated Variants_ doesn't actually add any ore generation, and certainly doesn't have any way to copy ore generation settings from one dimension to another - in fact, the entire system is built to be dimension-agnostic! This is what lets it be as easily extensible and config-controlled as it is. Basically, the mod doesn't know that dimensions exist.

With this in mind, if _another_ mod adds ore generation in different dimensions, it should be pretty easy to add that mod's ore gen to the config for *Excavated Variants* to get the various stone variants to generate.

All of this said, this is not something I plan on adding soon; I'll leave this open in case I find a way to do it that makes sense within the scope of the mod, but it's very low priority.

**Comment by lukebemish** [comment]
Closed, to the degree that I plan on doing this at this point in time, by #29
