### ISSUE TITLE
[BUG] Issue with... Version 2.2.0

### ISSUE THREAD

**Issue by drakosoldier298** [lukebemish/excavated_variants#111]
### What went wrong?

It is requesting dynamic asset generator version 3.0.2 which does not exist. Latest 3.0.1

### Platform

Forge

### Version

2.2.0

### Logs and Screenshots

https://mclo.gs/fxvRdzc

**Comment by lukebemish** [comment]
Whoops, I forgot to publish that. Let me do that before I forget. Thanks for submitting a report!

**Comment by drakosoldier298** [comment]
Wow such fast response im dying of laughter of how fast, thank you for fixing it. im very much not used to mod creators being fast at responding.

**Comment by lukebemish** [comment]
DynamicAssetGenerator 3.0.2 has been published and is pending aproval on CurseForge, or available now on modrinth.
