### ISSUE TITLE
Bug: Stuck on initial loading screen (before loading screen)

### ISSUE THREAD

**Issue by Herobattler** [lukebemish/excavated_variants#112]
### What went wrong?

Stuck on initial loading screen (before loading screen)

### Platform

Forge

### Version

1.19.2 - 1.0.3

**Comment by lukebemish** [comment]
I can't really do much without a log. Can you provide one? Also, are you using any resource packs (which ones?), optifine, or other mods that might affect resource loading?

**Comment by Herobattler** [comment]
[Resourcepacks.txt](https://github.com/lukebemish/excavated_variants/files/11012261/Resourcepacks.txt)
[Mods.txt](https://github.com/lukebemish/excavated_variants/files/11012263/Mods.txt)

**Comment by lukebemish** [comment]
Optifine is known to break DynAssetGen (and so Excavated Variaants) at times, and there's nothing I can do to fix it on my end - it's a bug on their end. I'm not sure that's the exact issue here - can you remove optifine, and then provide your debug.log file? I can't really do anything without that file.

**Comment by Herobattler** [comment]
It was slowing down during variants, right. It worked flawless whitout Optifine.

**Comment by lukebemish** [comment]
It works fine without optifine? Then yeah, nothing that I can do about it. This is an optifine bug
