### ISSUE TITLE
Ores not showing up anywhere

### ISSUE THREAD

**Issue by Herobattler** [lukebemish/excavated_variants#113]
### What went wrong?

The ores neither populate the creative tab nor the world.

### Platform

Forge

### Version

1.0.3

**Comment by lukebemish** [comment]
Could you provide a log file please?

**Comment by Herobattler** [comment]
[latest.log](https://github.com/lukebemish/excavated_variants/files/11072167/latest.log)

**Comment by lukebemish** [comment]
Hmm. I'd try deleting the Excavated Variants config, the defaultresources config if there is one, and the globalresources folder

**Comment by Herobattler** [comment]
Okay it works now, at least in the nether

**Comment by lukebemish** [comment]
Have you tried generating new chunks in the overworld? It only works there

**Comment by Herobattler** [comment]
I have a mod installed who makes all the ores spawn exclusively on the surface where stone meets air or cave air, could this be the reason that the ores rarely spawn or at all?

**Comment by lukebemish** [comment]
Possibly; it depends how that mod implements their changes, and whether they do it in a compatible way. Which mod? The way I implement stuff *should* be compatible with most mods.

**Comment by Herobattler** [comment]
the mod: https://www.curseforge.com/minecraft/mc-mods/caveore/files/3930777

**Comment by lukebemish** [comment]
Could be; it's hard to tell. The easiest way to check is to remove that, start up a new world, and see if that changed it. I can't see any obvious causes for an incompatibility there though

**Comment by Herobattler** [comment]
The mod could check for any changes to the ore spawn rules and follow them as instructed if this is possible as a fix, basically pretending to be a part of the regular ores

**Comment by lukebemish** [comment]
This mods processor runs after ores have been placed. It should have nothing to do with mods that modify ore placement. Have you tried removing that mod and checking if it is actually an incompatibility?

**Comment by Herobattler** [comment]
I have and it works fine now, I was able to find some of the new ores. I know the cave spelunking mod is very compatible with modded ores, so I have no clue whats going on.

**Comment by lukebemish** [comment]
Yeah, I'm not sure either. My system is designed to not care about how ores are placed - are you sure you didn't just get unlucky? Excavated Variants doesn't replace stuff on chunk or section borders necessarily, for instance

**Comment by Herobattler** [comment]
Iam 100 percent sure, i was searching for minutes through all kinds of  caves and hights, modded and vanilla and only the nether one while i was testing found some ore right away

**Comment by lukebemish** [comment]
I installed just DynAssetGen, Excavated Variants, and the mod you linked, all the latest versions for 1.19.2, and was unable to reproduce this issue; to clarify, are you seeing no ores at all or none of Excavated Variants' variants? And just to confirm, you did make a fresh world?

**Comment by Herobattler** [comment]
I was able to find some, however they seem to be very rare compared to the other ore spawn, so i guess issue resolved

**Comment by lukebemish** [comment]
The variants added by Excavated Variants only appear where the normal ores naturally appear next to the relevant stone; if there is no stone, if that helps you search for them. This means, by definition, that they will be less common than the default variants as there is less, say, granite than there is stone.
