### ISSUE TITLE
[ENHANCEMENT] Fabric port of newer version?

### ISSUE THREAD

**Issue by Merith-TK** [lukebemish/excavated_variants#115]
### What feature would improve this mod?

Not all mods for fabric are 100% functional for quilt, and this is one of the good onces that personally should be on *all* Modloaders for MC due to just how *good* it actually is.

### Why would this feature be useful?

See Above

### Is there any other relevant info about this feature request?

I am actually kinda curious why you chose to dive away from fabric entirely in favor of quilt for this?

### Mod Compatibility

- [X] This feature cannot be added through the config

**Comment by lukebemish** [comment]
Fabric has shown itself to be inflexible in its API design, and platforms transphobia. Frankly, given that quilt is pretty good about getting currently broken fabric mods to run on quilt if the appropriate issue reports are opened, I see no reason whatsoever to maintain any of my mods for fabric. If you have fabric mods that do not currently run on quilt, you should open issue reports either with quilt or with those mods authors (or with both, to keep everyone up to date).

**Comment by Merith-TK** [comment]
Fair enough on those points
