### ISSUE TITLE
[BUG] "Errors in currently selected datapacks..."

### ISSUE THREAD

**Issue by Eldog02** [lukebemish/excavated_variants#12]
**Describe the bug**
Cannot generate new world due to "Errors in currently selected datapacks" despite having no datapacks downloaded or enabled.

**To Reproduce**
1. Download latest version of Fabric API, Excavated Variants, Dynamic Asset Generator, Architectury (as of 3/17/22)
2. Create a new world with default settings
3. Prompted with datapack safe mode error screen

**Expected behavior**
World generates... at all, with excavated variants stone ores and no datapack errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/34759177/158786425-463598a2-3dc2-4c73-b771-ed68bc9ae26d.png)
![image](https://user-images.githubusercontent.com/34759177/158786472-846eaa68-0b82-4c2e-bc72-fdfab08aa7d8.png)

**Version:**
 - Fabric
 - Minecraft 1.18.2 - Excavated Variants 0.3.2

**Comment by lukebemish** [comment]
Logs please

**Comment by lukebemish** [comment]
Should be fixed in newest version. Bit of leftover 1.18.1->1.18.2 changes I'd not done correctly.
