### ISSUE TITLE
[BUG] [1.20.1] Unable to mine (this mod's) ores/no tool assigned to mine them

### ISSUE THREAD

**Issue by Zedrimar** [lukebemish/excavated_variants#125]
### What went wrong?

Unable to mine varient ores from this mod. TheOneProbe shows the ores as unmineable with no tool to mine them. I think this might be some weird mod interaction thing, but I can't for the life of me figure out what the hell it is. :/

I tested this mod by itself on a test install and it seems to work fine though. Strange....

Forge  1.20.1 47.0.14
MC: 1.20.1

### Platform

Forge

### Version

1.20.1 - 3.0.0

### Logs and Screenshots

![2023-06-20_17 23 35](https://github.com/lukebemish/ExcavatedVariants/assets/8153290/de4e6f44-7201-4006-98a6-905b876cb19e)

Debug Log: https://pastebin.com/RXpNnc5D

Latest Log: https://pastebin.com/6FwDf0LR

_________________________________________________
EDIT: I found the following in the log. Appears to be an issue loading the tool tags
https://pastebin.com/150Mbv52

I found no errors referring to this mod or the asset generator when running on a stand-alone test install

**Comment by lukebemish** [comment]
The heck... okay, I'll poke that. That's... rather suspicious. Makes me suspect some mod or another is doing something funky and not properly setting up their item tier, but I can shove some checks on it on my end

**Comment by lukebemish** [comment]
Right. Hmm. Yeah, some mod has just decided not to define a tag for their tiers. Oh well

**Comment by lukebemish** [comment]
If there're any blocks based on those tiers - I make no guarantees that they'll be properly added to the right mining tier. But otherwise, I should be able to fix this particular issue in the next version, which will be out in a few minutes

**Comment by Zedrimar** [comment]
Sadly didn't work. Still unsure what mod is causing it. Thanks trying though.

I keep finding the same error. I've been trying to add mods 1 by 1 with mods that add ores but so far nothing. If you want to poke around again, this is the updated debug log with the updated mod version: https://pastebin.com/eeEheNa7

**Comment by lukebemish** [comment]
I missed a spot, it seems. Next version should be fine.
