### ISSUE TITLE
[BUG] Issue with End Stone Being replaced by Apple Texture

### ISSUE THREAD

**Issue by Freshah** [lukebemish/excavated_variants#13]
Hi I've noticed a single texture being off...

![2022-03-20_10 21 11](https://user-images.githubusercontent.com/71207812/159167448-9d546d97-82fa-4cf3-a476-654b3e5b46e5.png)

On newest version of Excavated Variants and Dependencies

**Comment by lukebemish** [comment]
Oops, looks like I forgot to remove some debug code. I'll fix that shortly

**Comment by lukebemish** [comment]
Moved to lukebemish/dynamic_asset_generator#3

**Comment by lukebemish** [comment]
Should be fixed; update dynamic asset generator to v0.4.1 once it gets approved on curseforge.

**Comment by Freshah** [comment]
Thanks m8
