### ISSUE TITLE
[BUG] EV + Promenade causes loads of tags to fail + Textures to not load correctly

### ISSUE THREAD

**Issue by TrueDevron** [lukebemish/excavated_variants#130]
### What went wrong?

When using EV + Promenade the textures fail and according to the log file, a bunch of tags also fail to register. I've tried turning on/off cache and resetting my configs, nothing works.

Any idea what could be causing this?

### Platform

Quilt

### Version

3.0.2

### Logs and Screenshots

[latest.log](https://github.com/lukebemish/ExcavatedVariants/files/11911899/latest.log)

**Comment by lukebemish** [comment]
This will be fixed in the next update, which is building now. Let me know if it is still not working as that would mean there's more than one issue here

**Comment by lukebemish** [comment]
For some context on what went wrong - promenade renamed "carbonite" to "asphalt" and I needed to update the default configs in Excavated Variants to reflect that

**Comment by lukebemish** [comment]
Version 3.0.3 with this fix has been released. I will be out of town for a bit so if there are more issues involved here, I may not get to them for a while
