### ISSUE TITLE
[ENHANCEMENT] Excavated Variants x Croptosis

### ISSUE THREAD

**Issue by TheButterbrotMan** [lukebemish/excavated_variants#14]
https://www.curseforge.com/minecraft/mc-mods/croptosis

What needs to be done?

- Potash Ore
- Apatite Ore
- Deepslate Apatite Ore

**Comment by lukebemish** [comment]
A blanket statement being placed on all default config requests: I may or may not get around to adding any of these to the default configs. If *you* would like to, or have already, written configs for this mod/mods, feel free to open a pull request to add these configs. They should be placed under `common/src/main/resource/default_configs`. For the config format, see the CurseForge page.

**Comment by lukebemish** [comment]
I am going to close this and all similar issues; if you would like, please open a pull request with a default config for the relevant mod.
