### ISSUE TITLE
[1.20.x][BUG] Mining Level issue

### ISSUE THREAD

**Issue by Bass2style** [lukebemish/excavated_variants#142]
### What went wrong?

Hello,

Mining Level seems not correctly set in the mod.
ores are set to "no tool" for mining, and can't be mined.

### Platform

Forge

### Version

v3.0.4

### Logs and Screenshots

![2023-07-19_16 20 21](https://github.com/lukebemish/ExcavatedVariants/assets/29619787/d7af43c4-8945-47ae-8d1e-794c80d7a346)

**Comment by lukebemish** [comment]
Ah heck, this issue again. Log please, and what version of dynamic asset generator is installed

**Comment by Bass2style** [comment]
i'm using version 4.1.3 of DAG, and here is a Latest.log, but i did a lot of thing since i found this issue. xD : https://gist.github.com/Bass2style/784d15d2b35044a105eaf50862934ea6

**Comment by lukebemish** [comment]
This *should* be fixed in 3.0.5 once it releases

**Comment by lukebemish** [comment]
3.0.5 is released; let me know if that doesn't fix it

**Comment by Bass2style** [comment]
3.0.5 fixes the thing. thank you for your reactivity.
