### ISSUE TITLE
[BUG] Issue with... Mismatch Version

### ISSUE THREAD

**Issue by smithrm1984** [lukebemish/excavated_variants#149]
### What went wrong?

So we set up a server for our community, Multiblock Madness 2, we are getting the mismatched versions although they are not mismatched and saying failed to synchronize registry data from server. I followed a closed issue you had previously (issue #100) did that stuff server side. When I joined it created all the different ore deposits etc. in the console and i was able to connect, however none of our community members can join and are getting the mismatch error.

### Platform

Forge

### Version

0.6.5

### Logs and Screenshots

https://i.imgur.com/5LGPq5Z.png

![image](https://github.com/lukebemish/ExcavatedVariants/assets/46536516/676cf144-0039-4408-ad0c-db056332b6d2)

**Comment by lukebemish** [comment]
Hmm, that imgur link appears to be dead. I suspect what may have happened here is that that modpack bundles a custom config for Excavated Variants, and when you deleted the config on the server side, and on your end, those two now match but don't match the config anyone else has. What I would do:
- delete the config for both you and the server
- download a fresh version of the modpack, copy the Excavated Variants config from it, if there is one, to the server and your local install

Those two should then be set up right. Then, have any other clients unable to connect after doing that follow the same steps.

**Comment by smithrm1984** [comment]
Updated img, sorry about link not working. i will try in the morning and let you know what happens.

**Comment by smithrm1984** [comment]
Tried your steps but only worked for me, but not others w/o deleting their local configs then joining. However before doing this i could join modpack authors server just fine and not ours, i do the fix you suggested can connect to ours but not his afterwards. we might just scrap the idea of putting the server in our community. Needs more discussion on our end.

**Comment by lukebemish** [comment]
Hmm. Can you give me
- the full excavated variants config, zipped
- a log

from both ends of a connection that isn't working?

**Comment by smithrm1984** [comment]
Here are the files, server side there is no kind of log given so i included a snippit of the console messege when trying to connect. as far as client side i included a picture of the mismatch message and the "latest.log" file which i assume would be from client side server. there is a folder and individual config file in each one. The modpack author and I are thinking our server panel may be doing something different when it installs the server but outside that i am unsure.

[Excavated Variants - Server and client configs.zip](https://github.com/lukebemish/ExcavatedVariants/files/12307485/Excavated.Variants.-.Server.and.client.configs.zip)

**Comment by lukebemish** [comment]
So sorry for the delay; I've been rather busy. As this is 1.18.2 there's only so much I can do; a lot of the features I added to help debug stuff like this are only on newer versions. However, from the configs you've provided, and that log, it looks like the server is not generating several variants that the client expects. This could be due to an interaction with another mod - I'd check to see whether the geolosys config is the same between both, for instance! However, besides that I'm not sure what else to try. A solution is to add the problematic ore IDs to the ore type blacklist in the main config - in the `"blacklist_ores": []` line, add `"nether_gold_ore"` and `"ancient_debris_ore"` to the list.

**Comment by lukebemish** [comment]
Just following up; did that help at all?

**Comment by smithrm1984** [comment]
It didn't sorry, we just gave up on it.  You can close this issue. Thanks
for helping us out though.
