### ISSUE TITLE
[ENHANCEMENT] Excavated Variants x Mythic Metals

### ISSUE THREAD

**Issue by TheButterbrotMan** [lukebemish/excavated_variants#16]
https://www.curseforge.com/minecraft/mc-mods/mythicmetals

What needs to be done?
- Platinum Ore
- Tin Ore
- Adamantite Ore
- Deepslate Adamantite Ore
- Aquarium Ore
- Banglum Ore
- Nether Banglum Ore
- Carmot Ore
- Deepslate Carmot Ore
- Kyber Ore
- Calcite Kyber Ore
- Manganese Ore
- Morkite Ore
- Deepslate Morkite Ore
- Midas Gold Ore
- Mythril Ore
- Deepslate Mythril Ore
- Orichalcum Ore
- Tuff Orichalcum Ore
- Smooth Basalt Orichalcum Ore
- Deepslate Orichalcum Ore
- Osmium Ore
- Palladium Ore
- Prometheum Ore
- Deepslate Prometheum Ore
- Quadrillum Ore
- Runite Ore
- Silver Ore
- Starrite Ore
- Calcite Starrite Ore
- End Stone Starrite Ore
- Stormys Ore
- Blackstone Stormyx Ore
- Tin Ore
- Unobtainium Ore
- Deepslate Unobtainium Ore

**Comment by lukebemish** [comment]
You've left a lot of these recently. Your best bet is to make a pull request.

**Comment by lukebemish** [comment]
A blanket statement being placed on all default config requests: I may or may not get around to adding any of these to the default configs. If *you* would like to, or have already, written configs for this mod/mods, feel free to open a pull request to add these configs. They should be placed under `common/src/main/resource/default_configs`. For the config format, see the CurseForge page.

**Comment by lukebemish** [comment]
I am going to close this and all similar issues; if you would like, please open a pull request with a default config for the relevant mod.
