### ISSUE TITLE
No ore has the right texture

### ISSUE THREAD

**Issue by krjencik** [lukebemish/excavated_variants#162]
### What went wrong?

Im now in creative. What went wrong? See the screenshot.

### Platform

Forge

### Version

3.0.5

### Logs and Screenshots

![2023-09-07_15 09 18](https://github.com/lukebemish/ExcavatedVariants/assets/92643141/c631f951-9abe-4c86-8da8-e5b820046d70)

[latest.log](https://github.com/lukebemish/ExcavatedVariants/files/12549473/latest.log)

**Comment by krjencik** [comment]
strange - alone it works...................................

**Comment by lukebemish** [comment]
Looks like the compat config for Gems n Jewels is out of date or otherwise a bit funky; you could try disabling that. I'll try to get an update out soon to fix that and add some extra checks to prevent this happening, though how it got past my existing precautions is a bit funky

**Comment by lukebemish** [comment]
Should be fixed in 3.0.7 which will hopefully finish releasing in an hour or so. Let me know if it is not

**Comment by krjencik** [comment]
Ty, now it works. (prosperity, inferium ores look just like the block they are in...)

**Comment by lukebemish** [comment]
Oh lovely, that's an ongoing issue with Mystical Agriculture. I thought I'd fixed it but obviously something has changed. Feel free to open a new issue for it
