### ISSUE TITLE
[BUG] Issue with... Idk what is happening

### ISSUE THREAD

**Issue by krjencik** [lukebemish/excavated_variants#163]
### What went wrong?

i cant mine stone and ores

### Platform

Forge

### Version

3.0.7

### Logs and Screenshots

![2023-09-08_13 02 38](https://github.com/lukebemish/ExcavatedVariants/assets/92643141/699ba816-0cd2-47d9-b8ba-d82cf2923bc1)

[latest.log](https://github.com/lukebemish/ExcavatedVariants/files/12563255/latest.log)

**Comment by lukebemish** [comment]
Do you by chance have caching enabled for Dynamic Asset Generator? This was a bug I thought I fixed in 3.0.7 but if there's an old cache sitting around that would mess it up. If you do have caching enabled, delete the cache in the mod_data folder

**Comment by lukebemish** [comment]
If that doesn't work please share a debug.log

**Comment by krjencik** [comment]
i enabled both caches. No change. (I also deleted that old cache)
[debug.log](https://github.com/lukebemish/ExcavatedVariants/files/12565286/debug.log)

**Comment by lukebemish** [comment]
Ah, tracked down the issue. Will be fixed in 3.0.8, which will be released in an hour or so
