### ISSUE TITLE
[BUG] Issue with servers

### ISSUE THREAD

**Issue by TysonTheEmber** [lukebemish/excavated_variants#167]
### What went wrong?

When installing this mod on a server and client there will be mismatched stone mappings,

### Platform

Forge

### Version

excavated_variants-forge-1.19.2-1.0.3.jar

### Logs and Screenshots

![image](https://github.com/lukebemish/ExcavatedVariants/assets/101071342/047d8302-89fa-4bfb-9a72-56508989a545)

**Comment by lukebemish** [comment]
Yes, it's what the error says. You have different configs on the two sides for some reason. Either different mods exist in both sides, or different default compatibility configs are set up for Excavated Variants on each side. Try deleting the Excavated Variants compatibility config folders and config file on both sides and letting it regenerate, **making sure that you have the same versions of mods installed on both ends** (this is very important). If that doesn't work please provide logs from both sides

**Comment by TysonTheEmber** [comment]
The configs were the same and they had the same mod version.

![image](https://github.com/lukebemish/ExcavatedVariants/assets/101071342/b6f5b708-a33b-4aec-a079-50135b4527e9)
![image](https://github.com/lukebemish/ExcavatedVariants/assets/101071342/48f682fa-fc7b-431c-a5e0-7792a54d9535)

client- [latest.log](https://github.com/lukebemish/ExcavatedVariants/files/12707571/latest.log)

server- [latest.log](https://github.com/lukebemish/ExcavatedVariants/files/12707572/latest.log)

**Comment by TysonTheEmber** [comment]
I dont know why but I think it was a startup problem not genning the files correctly, I fixed the problem for now but I would still look out for it.

**Comment by lukebemish** [comment]
_All_ the configs were the same? You checked every single generated file? (They're in either config/excavated_variants or globalresources, depending on the version). Those ones don't necessarily update if you update the mod - you have to delete the normal config file and let them regenerate, generally

**Comment by TysonTheEmber** [comment]
Ok, it seems that the client just doesn't generate a proper mappings_cache.json5 file, it just generates a empty list
