### ISSUE TITLE
[ENHANCEMENT] I set up a file for Oreganized support with their Beta

### ISSUE THREAD

**Issue by Freshah** [lukebemish/excavated_variants#17]
Figured I should share it to save someone some time

```
{
  "mod_id": "oreganized",
  "provided_stones": [],
  "provided_ores": [
    {
      "id": "lead_ore",
      "stone": [
        "stone",
        "deepslate"
      ],
      "texture_location": "oreganized:textures/block/lead_ore.png",
      "block_id": [
        "oreganized:lead_ore"
      ],
      "en_name": "Lead Ore",
      "types": [
        "stone"
      ]
    },
   
    {
      "id": "silver_ore",
      "stone": [
        "stone",
        "deepslate"
      ],
      "texture_location": "oreganized:textures/block/silver_ore.png",
      "block_id": [
        "oreganized:silver_ore"
      ],
      "en_name": "Silver Ore",
      "types": [
        "stone"
      ]
    }
  
   
  ]
}
```

**Comment by lukebemish** [comment]
If you (or anyone else) feels like adding this into the defaults, feel free to make a pull request.

**Comment by lukebemish** [comment]
A blanket statement being placed on all default config requests: I may or may not get around to adding any of these to the default configs. If *you* would like to, or have already, written configs for this mod/mods, feel free to open a pull request to add these configs. They should be placed under `common/src/main/resource/default_configs`. For the config format, see the CurseForge page.

**Comment by lukebemish** [comment]
If you would like to transfer this to a pull request for a default config, that would be much appreciated.
