### ISSUE TITLE
[1.18.2][Forge] New configs for mods don't add new variants

### ISSUE THREAD

**Issue by V972** [lukebemish/excavated_variants#185]
MC: 1.18.2
Forge: 40.2.10
Dynamic Asset Generator: v0.6.3
Excavated Variants: v0.6.5

I added config for [Create: Dreams & Desires](https://modrinth.com/mod/create-dreams-and-desires), which adds Tin Ore and 3 stone variants - Gabbro, Potassic and Weathered Limestone.

Here's my file: [create_dd.json](https://github.com/lukebemishprojects/ExcavatedVariants/files/13796518/create_dd.json)

However, after restaring, several times even, no variants were added:
<details><summary>Limestone</summary>

![image](https://github.com/lukebemishprojects/ExcavatedVariants/assets/45125685/2a00e84b-5b97-4498-9bae-36f5d3304fa2)
</details>

<details><summary>Potassic</summary>

![image](https://github.com/lukebemishprojects/ExcavatedVariants/assets/45125685/f544bd51-852f-4df9-aac9-5476493a17bb)
</details>

<details><summary>Gabbro</summary>

![image](https://github.com/lukebemishprojects/ExcavatedVariants/assets/45125685/1b7f5569-523f-4156-aeb2-e7593d706c1d)
</details>

<details><summary>Tin Ore</summary>

![image](https://github.com/lukebemishprojects/ExcavatedVariants/assets/45125685/66bd5186-9e5a-4f9f-80ea-314680c6c3cf)
</details>

Meanwhile, when I edited Malum config by adding brilliant ore from 1.19 version, it added those new variants just fine
<details><summary>Click to open</summary>

![image](https://github.com/lukebemishprojects/ExcavatedVariants/assets/45125685/62213b7f-ad09-4383-bc6e-99bb61fa43be)
</details>

I checked other configs and seemingly I registered everything correctly, but new variants weren't added.

**Comment by lukebemish** [comment]
Please attach your latest log and preferably a debug log

**Comment by V972** [comment]
Hi, sorry for late reply.
Here's my [latest.log](https://github.com/lukebemishprojects/ExcavatedVariants/files/13801021/latest.log) and [debug.log](https://github.com/lukebemishprojects/ExcavatedVariants/files/13801022/debug.log) logs from

1. Launching MC
2. Creating a new world
3. Flying around a bit to generate chunks
4. Crashing with F3+C

Which means I can also attach [crash report](https://github.com/lukebemishprojects/ExcavatedVariants/files/13801045/crash-2023-12-31_14.00.12-client.txt) if you need it. 

Hope it helps.

**Comment by lukebemish** [comment]
Your create_dd.json file is not valid JSON. So it won't load
