### ISSUE TITLE
[ENHANCEMENT] Fabric 1.20.1

### ISSUE THREAD

**Issue by Rebel459** [lukebemish/excavated_variants#187]
This mod's amazing, and I see you've recently ported from quilt to fabric on 1.20.2+
As a modpack dev, it would be great if you could consider adding fabric support to 1.20.1 in the future as it is the main supported version by most mods/modpacks at the moment and would expand the availability of the mod to players and modpacks on 1.20.1.

Thanks for your time!

**Comment by lukebemish** [comment]
Fabric support will not be added for 1.20.1. Please use quilt. Your other fabric mods should run on quilt; if they do not, this can almost certainly be fixed either on the quilt end or on those mods' end

**Comment by lukebemish** [comment]
To add more information for anyone looking at this after the fact:

Excavated Variants relies on several APIs that fabric either does not have or implements badly. In 1.20.2+, as QSL/QFAPI was not ported yet, I decided to switch back to fabric in spite of this; I managed to basically re-implement many of these requirements myself. In 1.20.1, I cannot easily do so in some cases without making breaking changes - which I will not be doing within a single MC version. Thus, I can't and won't really be porting it to Fabric in 1.20.1 - especially as anyone wishing to use it alongside fabric mods can simply run it on quilt.

**Comment by Rebel459** [comment]
Thanks for the info! Makes perfect sense and I appreciate you taking the time to provide a detailed response

**Comment by NolanHewitt** [comment]
Is this still the case now? Quilt has been falling behind on updates which is causing multiple fabric mods to have issues on quilt. Fabric has been consistently updating for 1.20.1 and I'm wondering if that's made it more possible to create a fabric version for 1.20.1 more easily?

**Comment by lukebemish** [comment]
It's not out of the realm of possibility, but it is not a priority. As far as I know quilt still works fine for 1.20.1. I may eventually make such a port, but I have some major underlying toolchain changes that would be required for that, including changing how Dynamic Asset Generator works. I am not sure these are possible without breaking changes. I do not make breaking changes within an MC version.

**Comment by NolanHewitt** [comment]
Understandable. I mainly ask as quilt has been having more issues being compatible with fabric mods in my experience so I'm having to consider switching to fabric.
