### ISSUE TITLE
Game Freeze/Crash on loading second world

### ISSUE THREAD

**Issue by BioMasterZap** [lukebemish/excavated_variants#193]
On Fabric 1.20.4 with Excavated Variants 4.1.1, if you launch the game and enter a game world (new or old), if you exit back to the main menu the game will freeze if you attempt to enter a world (same or different I believe).

If you only launch the game and play in the one world, I noticed no issues and you can close the game just fine. But if you attempt to enter a second world, a crash report is generated and the game becomes non-responsive, which has always resulted in ending the program to get it to close for me.

 I tested this in a separate profile with only Excavated Variants, Dynamic Asset Generator, and Fabric API present. The crash report noted to report it to Excavated Variants alongside a log, so here is the Crash Report and Log.

Crash Report:
https://gist.github.com/BioMasterZap/67b53334f8ef22ec66d3cfb0a524aaa5

Log:
https://gist.github.com/BioMasterZap/41aeb04ae5c8d72a858090f6f38e4a69

**Comment by lukebemish** [comment]
Hmm, that's a weird one. Should be fixed in 4.1.2, which is releasing right now
