### ISSUE TITLE
Emissive Textures

### ISSUE THREAD

**Issue by ENC4YP7ED** [lukebemish/excavated_variants#196]
How to add emissive textures to the ores ?

**Comment by lukebemish** [comment]
What do you mean? That depends on how you are adding them in general. Ores like redstone ore - which aren't truly emissive but just have a light level - should just work out of the box. In terms of other stuff - that depends on what tool you're using to add emissive textures, which Minecraft does not have for blocks by default.

**Comment by ENC4YP7ED** [comment]
Like this here : https://www.planetminecraft.com/texture-pack/bare-bones-emissive/

in _e format

**Comment by lukebemish** [comment]
That uses optifine's special system, not a built in feature of Minecraft; Excavated Variants does not currently have any special support for it. You would have to manually add emissive textures for the blocks yourself

**Comment by ENC4YP7ED** [comment]
Yes I know but how if there are no textures in both mods (dynamic asset generator and ExcavatedVariants)

**Comment by lukebemish** [comment]
The mods generate the textures at runtime. They're still there, just not in the jar

**Comment by ENC4YP7ED** [comment]
Where do you have a file path or something ?

**Comment by lukebemish** [comment]
You can enable caching to see where they are placed
