### ISSUE TITLE
[BUG] [1.18.2] Error in Datapack prevent the world from loading 

### ISSUE THREAD

**Issue by xR4YM0ND** [lukebemish/excavated_variants#20]
### What went wrong?

The world wont load up after adding Excavated Variants & Dynamic Asset Generator

### Platform

Fabric

### Version

1.18.2 - 0.13.3

### Logs and Screenshots

![2022-04-03_14 58 11](https://user-images.githubusercontent.com/97298005/161429386-db3ca0da-ce70-4ff5-a71a-7bb8aed893f9.png)

[latest.log](https://github.com/lukebemish/excavated_variants/files/8404547/latest.log)

**Comment by lukebemish** [comment]
Can't do anything without ~~logs~~ (noticed you've got a log) and a list of other mods

**Comment by lukebemish** [comment]
Also... 0.13.3 isn't a version of this mod. What version *of Excavated Variants* do you have installed?

**Comment by xR4YM0ND** [comment]
0.13.3 is the fabric loader version 
Minecraft Fabric version : 1.18.2

Dynamic Asset Generator 0.4.1
Excavated Variants 0.4.0

**Comment by lukebemish** [comment]
Can you turn on asset and data caching, and show me what is in the cache in data/minecraft/tags/blocks/needs_diamond_tool.json?

**Comment by lukebemish** [comment]
I have a suspicion what went wrong; it looks like some other mod did weird stuff while registering tags, and didn't specify a replace value. I could still use what that cached file looks like, but I'll try to get around to fixing it this week sometime.

**Comment by lukebemish** [comment]
Should be fixed in the newest versions of Excavated Variants and Dynamic Asset Generator, once they finish uploading.
