### ISSUE TITLE
Rare server crash in End dimension with Better End (Quilt, 1.20.4)

### ISSUE THREAD

**Issue by Soulfate24** [lukebemish/excavated_variants#204]
I had a rare random crash (server) in the End dimension (Quilt, 1.20.4), using Better End. Here is the log:
https://pastebin.com/LBFw5NFA

I'm currently hard modding Minecraft, so I spend a lot of time exploring world looking for bugs ;)
Thank you!

**Comment by lukebemish** [comment]
Should be fixed in the next release (releasing now), let me know if it isn't.
