### ISSUE TITLE
[Enhancement] Add #forge:ores_in_ground/{stone_type}

### ISSUE THREAD

**Issue by Ghastly13** [lukebemish/excavated_variants#223]
It seems like there's already the associated #c:ores_in_ground/{stone_type} tag, so it would probably make sense to cover all the bases.

**Comment by lukebemish** [comment]
In 1.20.4, where neoforge still used `forge:xyz` tags, there _is_ a `forge:ores_in_ground/stone_type` tag. It was switched to the `c` variety in newer versions where nobody should be using `forge:` tags as neoforge now uses `c:` convention tags. As such, having the `forge:` variety (of this or any other tag) makes no sense

**Comment by Ghastly13** [comment]
Which versions are supported? The tag isn't added in Forge 1.20.1

**Comment by lukebemish** [comment]
Nor is the equivalent`c:` tag. The data structure that generates ores is structured a bit differently then and does not have the appropriate information to add that tag, of either the c or forge variant.
