### ISSUE TITLE
neoforge 1.21.1 extremely slow mining issue

### ISSUE THREAD

**Issue by VaporeonScripts** [lukebemish/excavated_variants#232]
any excavated variant ore is extremely slow to mine (takes 20+ sec) for example an andesite iron ore takes like 20 seconds to mine with an iron pickaxe and doesnt even drop the ore

**Comment by VaporeonScripts** [comment]
https://streamable.com/xiqhzq

**Comment by lukebemish** [comment]
Hmm. Seems like it's not ending up in the proper tags to let it be pickaxe mineable -- can you share your mod list? Last time this happened it was a conflict with another mod.

**Comment by VaporeonScripts** [comment]
well, its a bit long but sure :D
https://mclo.gs/GCs0xJP

**Comment by lukebemish** [comment]
Can you re-install the mod "tide" making sure it's on the most recent version? This looks suspiciously similar to https://github.com/lukebemishprojects/ExcavatedVariants/discussions/231

**Comment by VaporeonScripts** [comment]
checked,its the latest possible version, but sure

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/e59dc8ac-1c46-449d-92b1-ab0270590af4)
reinstalled

**Comment by lukebemish** [comment]
Alright. Could you provide a full log then, if that didn't fix it?

**Comment by VaporeonScripts** [comment]
alright
https://mclo.gs/dJybk9V

**Comment by VaporeonScripts** [comment]
tide fixed the issue
