### ISSUE TITLE
all excavated variants have buggy purple texture

### ISSUE THREAD

**Issue by VaporeonScripts** [lukebemish/excavated_variants#236]
https://mclo.gs/auDkq9N
![image](https://github.com/user-attachments/assets/0c16e455-5814-41cb-a92d-7dffa371823d)

**Comment by VaporeonScripts** [comment]
incompatibility with all the trims
https://github.com/Bawnorton/AllTheTrims/issues/49#issue-2600790676

**Comment by Bawnorton** [comment]
Fixed https://github.com/Bawnorton/AllTheTrims/issues/49#issuecomment-2425214736

**Comment by lukebemish** [comment]
Huh, that's quite the interaction to pop up! Thanks for letting me know it's fixed and what the cause was.

**Comment by VaporeonScripts** [comment]
No problem
