### ISSUE TITLE
[HELP] Changing the variant default ore texture

### ISSUE THREAD

**Issue by DaddySpin** [lukebemish/excavated_variants#238]
I have multiple mods that add silver ore and i have removed all of them spawning in the world but any off the variants that spawn have the silver texture from galosphere when i want them to use the texture from Create: Unify and im lost on how to achieve this.

**Comment by lukebemish** [comment]
Assuming this is 1.20.1 or so -- you'll want to change the config so that only the particular ore block you want is added to the silver ore variant.

**Comment by DaddySpin** [comment]
Sorry forgot to mention this was 1.20.1, but can you give me an example? I have already tried extracting the config like it says on the Modrinth page and I'm not getting any results.

**Comment by lukebemish** [comment]
What do you mean that you haven't gotten any results? What exactly have you done, and what are the results?

**Comment by DaddySpin** [comment]
![Code_edGe6F2PLu](https://github.com/user-attachments/assets/4d6606dc-f4c8-4dae-97e1-053935a52a71)
![explorer_VUC96SK4wj](https://github.com/user-attachments/assets/f92e50de-218d-4b4b-babf-505700511da8)
I tried extracting the config and it doesn't generate any files in the global resources folder after launching the game.

**Comment by lukebemish** [comment]
Then please provide a log

**Comment by DaddySpin** [comment]
[latest.log](https://github.com/user-attachments/files/17882405/latest.log)
This is the latest log after creating the config file and running the game once.

**Comment by DaddySpin** [comment]
I realized what i was doing wrong. i was creating a config file in the globalresources folder instead of editing the one in the config folder.

**Comment by DaddySpin** [comment]
btw do i leave the zip file zipped to edit the default config or do i extract it?
![image](https://github.com/user-attachments/assets/18b151dd-79f4-4d2b-bbf3-6c3d57b45284)

**Comment by lukebemish** [comment]
Either way should in theory work fine

**Comment by DaddySpin** [comment]
Okay thank you.
