### ISSUE TITLE
[1.18.2] Mod is preventing me from entering or making a world even when it's disabled

### ISSUE THREAD

**Issue by vizthex123** [lukebemish/excavated_variants#239]
I added some custom support, but opted to delete the entire config after realizing it was causing issues.

I've got no clue what's causing this, but it didn't happen until after i added custom ore & stone support.

Here's my game log:
[latest.log](https://github.com/user-attachments/files/17894259/latest.log)

And the forge debug log, just in case that helps:
[debug.log](https://github.com/user-attachments/files/17894260/debug.log)

**Comment by lukebemish** [comment]
The mod does not appear to be disabled in that log? In terms of what the issue is -- hard to tell from that log on its own without some idea what your setup looks like, but you appear to have some config, probably specified in the main config's ordering requirements, that does not exist:
```
[24Nov2024 11:40:15.778] [pool-4-thread-1/ERROR] [excavated_variants/]: Could not find referenced config: geolosys.json
```
That shouldn't prevent the world from loading on its own -- what does it look like when it doesn't load? Do you get some particular screen? Please provide more details.

**Comment by vizthex123** [comment]
> The mod does not appear to be disabled in that log? In terms of what the issue is -- hard to tell from that log on its own without some idea what your setup looks like, but you appear to have some config, probably specified in the main config's ordering requirements, that does not exist:
> 
> ```
> [24Nov2024 11:40:15.778] [pool-4-thread-1/ERROR] [excavated_variants/]: Could not find referenced config: geolosys.json
> ```
> 
> That shouldn't prevent the world from loading on its own -- what does it look like when it doesn't load? Do you get some particular screen? Please provide more details.

like i said, i only get the usual "errors in datapacks prevent the world from loading" screen with no extra details at all - and fully removing Excavated Variants doesn't fix it either.

i don't know why it's failing to find that config, as all i've done to the main config is disable conversion recipes. I deleted both the folder and main config once again, and the same thing is still happening.

here's the logs i get after removing excavated variations:

[latest.log](https://github.com/user-attachments/files/17895640/latest.log)

[debug.log](https://github.com/user-attachments/files/17895641/debug.log)

i can send you the modpack if you want to do some further testing.

**Comment by lukebemish** [comment]
Removing the mod entirely will prevent old worlds from loading, yeah -- that's just how worldgen works. You can't remove a mod with worldgen stuff and expect it to work. As for why the config is not working -- please send all excavated variants configs you have currently.

**Comment by vizthex123** [comment]
yes, i know that (even though it in old versions it would load the world and just delete any missing stuff - still salty modern MC doesn't do that) - but the fact that it prevents me from making a new world is a the greater issue

i removed all my custom stuff, so it's just the mod defaults - but here you go.
[excavated_variants.zip](https://github.com/user-attachments/files/17924807/excavated_variants.zip)

**Comment by vizthex123** [comment]
made a new instance and copied over the mods (after removing Excavated Variants and Dynamic Asset Generator), resource packs, and my custom scripts - and i'm still getting the same error. Tried making a new world and entering an old backup of my broken world (made it back in may, well before even discovering this mod iirc).

here's the new log:
[latest.log](https://github.com/user-attachments/files/17964500/latest.log)

deleting my KubeJS server scripts folder fixed it (even though i removed the 3 references to this mod it had? Only one script did so - one that added custom tags to a few ores). Re-adding all the scripts makes it give the same error.

seems like my ore smelting fixer script was the culprit, but i've got no clue why. I'll just rewrite it, i guess.

tested once more after reinstalling Excavated Variants (and adding my custom configs) and it worked. I guess i got a line or two wrong in KubeJS and that broke everything (but didn't say so in the log, because of course it didn't lol).

thanks again for taking a look at this random-ass world corruption.
