### ISSUE TITLE
Help with configs

### ISSUE THREAD

**Issue by baronpalmer** [lukebemish/excavated_variants#243]
I can't figure out the how the folder structure is suppose to be made, I followed the README: globalresources/[folder/pack]/globaldata/[namespace]/excavated_variants/ore but anything I put inside it doesn't generate the variants.
After trying over and over I eventually put my jsons inside the extracted default resources and it worked but only partially. The ores I added only generated andesite, diorite, and granite variants compared to everything else generating create and other modded stone variants.
Some help would be appreciated

**Comment by lukebemish** [comment]
Please zip your entire global resources folder and share it. I can do very little to help without knowing what you were doing.

**Comment by baronpalmer** [comment]
[globalresources.zip](https://github.com/user-attachments/files/18270903/globalresources.zip)

AlmostUnified was messing with the ores so I fixed that and it works inside the extracted variants folder now but i'm still not sure how my own directory is suppose to be structured
