### ISSUE TITLE
[ENHANCEMENT] Nether Gold Ore variation in Nerher stones instead of Overworld Gold.

### ISSUE THREAD

**Issue by cowsha** [lukebemish/excavated_variants#26]
### What feature would improve this mod?

![изображение](https://user-images.githubusercontent.com/35926994/163504838-fd96027c-7c30-4943-8951-9e99c713ddc5.png)
I suggest to replace Gold Ore with Gold Chunk Ore in Nether.

### Why would this feature be useful?

Having default Overworld ore here is kinda strange imho.

### Is there any other relevant info about this feature request?

Idk if this can be done through config or not. 
I think of it as some default config issue.

### Mod Compatibility

- [X] This feature cannot be added through the config

**Comment by lukebemish** [comment]
This can sort-of be done through the config, but the tags and compat of that sort won't line up right. I'll get to this once I switch over the config system to use a Codec instead of just a Gson reader.

**Comment by cowsha** [comment]
Thanks!

**Comment by lukebemish** [comment]
Closed by #29
