### ISSUE TITLE
Exception in server tick loop I java.util.concurrent.CompletionException

### ISSUE THREAD

**Issue by TheButterbrotMan** [lukebemish/excavated_variants#3]
I am experiencing a crash, while exploring.

https://bytebin.lucko.me/5BrwlTxgEh

**Comment by lukebemish** [comment]
Huh, I wasn't aware you could get a concurrent modification exception there. Should be an easy fix; I'll have an update today or tomorrow.

**Comment by lukebemish** [comment]
About how often would this crash occur?

**Comment by TheButterbrotMan** [comment]
I dont know, appeared one time while testing my modpack, i didpost it directly here.

Really looking forward for this update, want to include it!!!

**Comment by lukebemish** [comment]
Sure. I'll probably bundle some more default configs in with the fix once I get it working, and release it soon enough.

**Comment by TheButterbrotMan** [comment]
Also are you considering making this work in nether and end also?

**Comment by lukebemish** [comment]
It should already work in the nether or end. In fact, it can work in any dimension if the configs are added.

**Comment by lukebemish** [comment]
The default config should already add, for instance, basalt and blackstone nether quartz ore.

**Comment by TheButterbrotMan** [comment]
> I am experiencing a crash, while exploring.
> 
> https://bytebin.lucko.me/5BrwlTxgEh

Is also happening while idling.

**Comment by lukebemish** [comment]
Cool. It should be fixed once I release the new update. Was the crash log the same for the idling crash?
