### ISSUE TITLE
[ENHANCEMENT] Lightstones compat

### ISSUE THREAD

**Issue by Sunconure11** [lukebemish/excavated_variants#32]
### What feature would improve this mod?

Lightstones adds a number of ores to the game. I would make a config to PR over myself but sadly, I cannot, due to hardware issues.

### Why would this feature be useful?

Would make ores line up better with stones and such

### Is there any other relevant info about this feature request?

Ores glow up, like redstone sort of

### Mod Compatibility

- [X] This feature cannot be added through the config

**Comment by lukebemish** [comment]
What sort of hardware issues let you make an issue but not a pull request? Closing as this sort of thing belongs in a pull request. If someone else wants to make one, or if you choose to later, that is fine, but please don't open an issue for it.

**Comment by Sunconure11** [comment]
PSU issues. My computer is currently not with me at the moment. I cannot do code from mobile.

**Comment by lukebemish** [comment]
In that case, you also cannot play Minecraft from mobile, so this will not be relevant until you can anyways. I am sorry if this is coming across as a bit terse; I simply went to some length to put that checkbox there.

**Comment by Sunconure11** [comment]
Alright
