### ISSUE TITLE
[BUG] creative menu crash

### ISSUE THREAD

**Issue by WarlordWossman** [lukebemish/excavated_variants#34]
### What went wrong?

When switching page to see more creative menu tabs (the one from this mod) the game crashes instantly.

### Platform

Fabric

### Version

see crash report

### Logs and Screenshots

https://pastebin.com/YUPeNNpD

**Comment by lukebemish** [comment]
I need the whole log, not just the crash report.

**Comment by lukebemish** [comment]
Fixed by newest commit.
