### ISSUE TITLE
[BUG] Server crashes while starting

### ISSUE THREAD

**Issue by TheButterbrotMan** [lukebemish/excavated_variants#35]
### What went wrong?

I tried to start my dedicated modpack server and it crashes.

### Platform

Fabric

### Version

0.5.2

### Logs and Screenshots

https://bytebin.lucko.me/Lboabwq1nz

**Comment by lukebemish** [comment]
Oops, should be an easy fix. Give it a few minutes

**Comment by lukebemish** [comment]
Fixed in 0.5.4

**Comment by TheButterbrotMan** [comment]
thank you

**Comment by TheButterbrotMan** [comment]
Question, does this bugfix also come to fabric?

> Fixed in 0.5.4

**Comment by lukebemish** [comment]
Yes, curseforge just died for a bit and wouldn't let me upload the file

**Comment by TheButterbrotMan** [comment]
nvm its there thank you :)
