### ISSUE TITLE
[BUG] Persistent Missing Textures

### ISSUE THREAD

**Issue by BigBantha0** [lukebemish/excavated_variants#38]
### What went wrong?

Andesite versions of Copper, Coal, and Iron have no textures. No textures are generated by DAG.
I have enabled caching for DAG.
I have made my own textures and labelled them as the cached models specify (IE andesite_coal_ore37, andesite_iron_ore40) and placed them with all other textures.
I have tried reinstalling both DAG and EV, as well as deleting all files/folders associated in the \config folder.
I have no idea

### Platform

Forge

### Version

EV 0.5.5 / DAG 0.5.2

### Logs and Screenshots

![2022-05-03_22 51 05](https://user-images.githubusercontent.com/104882802/166624604-c6d4b584-c7a4-4d4c-9d39-3655c28aab4c.png)
![2022-05-03_22 51 13](https://user-images.githubusercontent.com/104882802/166624614-aa19dc34-b502-423a-92d5-5fb386471b53.png)

**Comment by BigBantha0** [comment]
Addendum: packaging the textures in a resource pack does work. Do not know the implications of this.

**Comment by lukebemish** [comment]
Have you tried deleting the cache?

**Comment by lukebemish** [comment]
Otherwise, please paste both your logs and the cached models and blockstates here.

**Comment by lukebemish** [comment]
Also, do you have any texture packs?

**Comment by lukebemish** [comment]
If so, go into the configs for EV and increase the texture count of the ores and stones up to the proper amount.

**Comment by lukebemish** [comment]
Any updates on this? I suspect it is either due to a non-reset cache or a texture pack that adds lots of ore/stone textures; if it is the first, reset your cache. If it is the second, increase the texture count in the configs. If neither works, please let me know what the cached models and blockstates look like.

**Comment by BigBantha0** [comment]
Sorry about not replying sooner; It seems to have been the former, as doing so resolved the issue
