### ISSUE TITLE
[BUG] Issue with ores not having a mining level

### ISSUE THREAD

**Issue by StockiesLad** [lukebemish/excavated_variants#39]
### What went wrong?

Excavated Variants' ores do not have a mining level. e.g. banglum ore variant should have a diamond mining level but instead just requires any pickaxe. It breaks progression... Any fix?

### Platform

Fabric

### Version

0.4.2

### Logs and Screenshots

Client
[latest.log](https://github.com/lukebemish/excavated_variants/files/8669565/latest.log)
Server
[latest.log](https://github.com/lukebemish/excavated_variants/files/8669566/latest.log)

I am going to update & test on singleplayer world too!

**Comment by lukebemish** [comment]
Fixed on newer versions

**Comment by StockiesLad** [comment]
> Fixed on newer versions

oh ok thanks!
