### ISSUE TITLE
Fabric build appears to have some compat issues with Dashloader

### ISSUE THREAD

**Issue by Sunconure11** [lukebemish/excavated_variants#4]
Something about it causes the game to deadlock if the two mods are installed.

It is either this mod, or Dynamic Asset Loader

Example of what I mean:

![image](https://user-images.githubusercontent.com/5614902/154449734-201a1760-8d37-4a8d-a748-5c563297dc33.png)

**Comment by lukebemish** [comment]
Probably dynamic asset loader and dashloader. I can look at it later, but if it's what I think it is, it's an issue caused by dashloader.

**Comment by lukebemish** [comment]
Sure. I guess my question is, what about your setup is different from mine? Have you tried resetting the cache/configs?

**Comment by Sunconure11** [comment]
Well, my configs are at the default settings, and I had tried clearing the cache

**Comment by lukebemish** [comment]
Try deleting all your configs, and the cache, and then re-run it.

**Comment by lukebemish** [comment]
And make sure you're on the latest versions.

**Comment by lukebemish** [comment]
If the issue persists, try to get me a log; I can't really do anything without a log.
