### ISSUE TITLE
[BUG] EV 0.5.5 load-time lag with large numbers of ores/stones

### ISSUE THREAD

**Issue by StockiesLad** [lukebemish/excavated_variants#40]
### What went wrong?

Game taking forever to boot!

### Platform

Fabric

### Version

0.5.5

### Logs and Screenshots

[latest.log](https://github.com/lukebemish/excavated_variants/files/8669908/latest.log)

**Comment by StockiesLad** [comment]
it's still booting...

**Comment by StockiesLad** [comment]
Had to force close it

**Comment by StockiesLad** [comment]
It seems to stop at a certain part of loading...

**Comment by StockiesLad** [comment]
I'm clearing all configs
lets see...

Nope... didn't work

**Comment by lukebemish** [comment]
What version of dynamic asset generator do you have installed?

**Comment by lukebemish** [comment]
Can you also give me the full latest.log and the debug.log?

**Comment by StockiesLad** [comment]
I tried 0.5.1 and 0.5.2 and i'm sending logs rn

**Comment by lukebemish** [comment]
(And yes, if you updated from an older version then you need to clear out your configs)

**Comment by StockiesLad** [comment]
> Can you also give me the full latest.log and the debug.log?

If debug.log is in logs, it isn't here. Is it in a different location?

**Comment by StockiesLad** [comment]
[latest.log](https://github.com/lukebemish/excavated_variants/files/8670088/latest.log)
Here is the log

**Comment by StockiesLad** [comment]
> (And yes, if you updated from an older version then you need to clear out your configs)

I cleared all configs, same issue

**Comment by StockiesLad** [comment]
> > Can you also give me the full latest.log and the debug.log?
> 
> If debug.log is in logs, it isn't here. Is it in a different location?

I indexed the gamedir, couldn't find it

**Comment by lukebemish** [comment]
Are you using the CF launcher? If so, there's a setting somewhere you have to turn on to get the debug.log

**Comment by StockiesLad** [comment]
> Are you using the CF launcher? If so, there's a setting somewhere you have to turn on to get the debug.log

I'm using the technic launcher

**Comment by lukebemish** [comment]
Well, probably the same deal. There's more debug information in that log, so I need it to be able to do much. Additionally, have you tried removing other mods to see if it's caused by something else?

**Comment by StockiesLad** [comment]
Yes I have. And also will the vanilla launcher suffice?

**Comment by StockiesLad** [comment]
Bc I'll move my mods there to get the debug.log

**Comment by lukebemish** [comment]
Yes, the vanilla launcher should produce a debug.log

**Comment by StockiesLad** [comment]
Minecraft apparently assumes we both have infinite time....

**Comment by StockiesLad** [comment]
Sorry for the wait

**Comment by StockiesLad** [comment]
Also, I'm using fabric loader 0.14.5 if that helps...

**Comment by StockiesLad** [comment]
Ok... finally MC finished installing 1.18.2

**Comment by StockiesLad** [comment]
It isn't making a debug.log bc it hasn't got there yet. So we gotta wait until it makes one it seems

**Comment by StockiesLad** [comment]
Does a debug.log appear during startup?
because if this is supposed to, it isn't here... I'm still booting

**Comment by StockiesLad** [comment]
Maybe the default configs are causing issues? Idk

**Comment by lukebemish** [comment]
If you have a latest.log, there should be a debug.log

**Comment by StockiesLad** [comment]
there isn't one, even in the vanilla launcher?

**Comment by lukebemish** [comment]
There might be a setting in the launcher you need to enable for it

**Comment by StockiesLad** [comment]
Any known mod incompatibilities that may be causing this?
I got no idea what it might be

**Comment by lukebemish** [comment]
No, but I can think of potential problems other mods might cause. Can you do a binary search to isolate the problematic mod?

**Comment by StockiesLad** [comment]
I'm going to give it 16Gb of ram and see what happens...

**Comment by lukebemish** [comment]
This is not a RAM issue

**Comment by lukebemish** [comment]
Unless you're only giving it something like 2 now

**Comment by lukebemish** [comment]
I need either a debug.log, or for you to isolate which other mod is causing the issue, in order to do much with this.

**Comment by StockiesLad** [comment]
nope... It just uses it all and does the same thing.
I think it's time to binary search. I'll let u know what is causing it.

**Comment by StockiesLad** [comment]
> I need either a debug.log, or for you to isolate which other mod is causing the issue, in order to do much with this.

there is no debug.log so I am goin to binary seach

**Comment by StockiesLad** [comment]
and nail down this mod

**Comment by StockiesLad** [comment]
It seems to be happening with many mods, I also saw in the log, it trying to guess the texture location... this might be related to it.

**Comment by StockiesLad** [comment]
[2022-05-12-5.log](https://github.com/lukebemish/excavated_variants/files/8670626/2022-05-12-5.log)

**Comment by StockiesLad** [comment]
I reckon it could be the removal of the texture locations that caused this...

**Comment by StockiesLad** [comment]
It happens with many mods...

**Comment by StockiesLad** [comment]
but because I have so much mods that excavated variants supports, it slows it down so much it can barely load

**Comment by StockiesLad** [comment]
Maybe add a config to re-enable manual texture path override?

**Comment by StockiesLad** [comment]
If this is indeed the cause

**Comment by StockiesLad** [comment]
Yeah, I just added mythicmetals and It slowed it down even more. I'll add back only the content mods that it supports and see if it happens.

**Comment by StockiesLad** [comment]
Yep it slows it down completely disproportionately

**Comment by StockiesLad** [comment]
![image](https://user-images.githubusercontent.com/60066663/167872794-1d983544-5a6e-451d-be8d-acf92af70c69.png)

**Comment by StockiesLad** [comment]
> This is not a RAM issue

This was bc the CPU usage was a bit lower than normal, so I thought it needed more RAM to eat up. But it isn;t the case

**Comment by StockiesLad** [comment]
33.85 Sec without these aforementioned mods;
2:37.69 sec with them
Default modpack loading time with every single mod (and earlier version of EV and Dynamic asset generator): ~2:30 sec

Simply by adding 10 mods, it increased loading time by 5x

**Comment by StockiesLad** [comment]
Even further proof. I deleted all the .json and kept 1 without any block or ore information and everything is launching properly

**Comment by StockiesLad** [comment]
![image](https://user-images.githubusercontent.com/60066663/167875767-ea05d70e-2963-45ac-9378-80308ea4ab88.png)

**Comment by lukebemish** [comment]
The texture location guessing is completely irrelevant; that has no performance impact at all. The load time *will* increase a ton as you add more mods, since the number of registered blocks goes up as the square of the number of mods added; this is because the mods generally add both stones and ores. If you have 20 supported stones and 20 supported ores, that's 400 blocks total, which is an enormous performance draw.

**Comment by StockiesLad** [comment]
> The texture location guessing is completely irrelevant; that has no performance impact at all. The load time _will_ increase a ton as you add more mods, since the number of registered blocks goes up as the square of the number of mods added; this is because the mods generally add both stones and ores. If you have 20 supported stones and 20 supported ores, that's 400 blocks total, which is an enormous performance draw.

Why did It work before decently...

**Comment by lukebemish** [comment]
Likely because I added more modded compat in newer versions

**Comment by lukebemish** [comment]
So there's more stones and ores that it recognized

**Comment by lukebemish** [comment]
Can you remove half of those mods, reset the configs, and see if it boots well then?

**Comment by StockiesLad** [comment]
Just those mods or with all the libs like before?

**Comment by lukebemish** [comment]
Keep all the mods as you normally have, but remove half of those that EV supports

**Comment by StockiesLad** [comment]
ok

**Comment by lukebemish** [comment]
Or just remove half of the configs from the EV folder (making sure you keep the `minecraft` one or loading may fail)

**Comment by StockiesLad** [comment]
ok.

**Comment by lukebemish** [comment]
Additionally: what sort of RAM/processor does your computer have, and how much RAM do you have allocated?

**Comment by StockiesLad** [comment]
8Gb Ram allocated out of 32GB 3200mhz RAM, ryzen 5 2600

**Comment by lukebemish** [comment]
Okay; If you could get me a visualVM snapshot of your game loading, that would potentially let me figure out if it's caused by my stuff. Otherwise, it's likely that you've just got too much stuff you're trying to load; Minecraft isn't meant to handle 400+ blocks at once.

**Comment by StockiesLad** [comment]
> Okay; If you could get me a visualVM snapshot of your game loading, that would potentially let me figure out if it's caused by my stuff. Otherwise, it's likely that you've just got too much stuff you're trying to load; Minecraft isn't meant to handle 400+ blocks at once.

If it gets cached, it should be fine then right?

Also, why is it so much more difficult to do it now? The older versions did it just fine...

**Comment by StockiesLad** [comment]
> Okay; If you could get me a visualVM snapshot of your game loading, that would potentially let me figure out if it's caused by my stuff. Otherwise, it's likely that you've just got too much stuff you're trying to load; Minecraft isn't meant to handle 400+ blocks at once.

It loaded, just slower...

**Comment by lukebemish** [comment]
It has nothing to do with caching; it's the actual blocks causing the issue, I suspect, not the textures. It is an issue now, likely, because there is support for more mods in new versions of EV, so there are more blocks being loaded. You can try caching stuff and see if that helps; it may.

**Comment by StockiesLad** [comment]
I manually added support for all my mods though, this new config actullay has less support. Anyways I won't be able to reply after this because I'm going to sleep. Thank you for your time!

**Comment by lukebemish** [comment]
Alright; I can look for a memory leak or the like, which could cause this and could potentially be caused by a weird mod interaction, but I'd need a visualvm snapshot or the like.

**Comment by FluffyBumblee** [comment]
![image](https://user-images.githubusercontent.com/60066663/167983929-f359919e-8afa-4dfd-b2e9-a12d04656546.png)
that's all the blocks, I had like 7 pages before. Also the latest version doesn't fix the mining level...

**Comment by StockiesLad** [comment]
I do not know how to use VisualVM. Sorry for that...

**Comment by lukebemish** [comment]
Latest version should fix the mining level, unless another mod is not using the tags right. Turn on caching and let me know what's in the appropriate tags in the cache. As for the performance stuff, there's not much I can do without a snapshot, as I'm not really seeing this on my end.

**Comment by StockiesLad** [comment]
> Latest version should fix the mining level, unless another mod is not using the tags right. Turn on caching and let me know what's in the appropriate tags in the cache. As for the performance stuff, there's not much I can do without a snapshot, as I'm not really seeing this on my end.

I just realised the old configs were in there my bad. I also installed VisualVM and the instance didn't appear on it. Is there a way to get it to show.

**Comment by lukebemish** [comment]
I'm not really sure; I haven't used it on minecraft before

**Comment by StockiesLad** [comment]
> I'm not really sure; I haven't used it on minecraft before

I'm assuming that you want me to profile it and send you the results.

**Comment by lukebemish** [comment]
Yeah. That would help me tell if there's a memory leak, and the potential cause.

**Comment by StockiesLad** [comment]
Also, if you maybe want to do a more advanced test, It is on a public modpack (that I made). I can send you the link if you want it.

**Comment by lukebemish** [comment]
That would help, yes

**Comment by StockiesLad** [comment]
https://www.technicpack.net/modpack/the-limit-reborn-1181.1905659

**Comment by StockiesLad** [comment]
Keep in mind, the EV is still out of date as it is still in testing rn.

**Comment by StockiesLad** [comment]
The directory to the mods will be in :
AppData\Roaming\.technic\modpacks\the-limit-reborn-1181\mods

**Comment by StockiesLad** [comment]
BTW, sorry for this headache. You probably had some other things you wanted to do and this issue has been dragging on for a while. Sorry for that.

**Comment by StockiesLad** [comment]
Another thing, I resetted all the configs and the mining level still isn't there...

**Comment by StockiesLad** [comment]
The game even still takes a long time to boot without any other mod except the ones that are directly supported by the EV configs

**Comment by StockiesLad** [comment]
![image](https://user-images.githubusercontent.com/60066663/167990355-4675c5ce-3e0d-47ec-813c-d3e7f404108b.png)
2:18.76 min/sec/ms time for loading these mods.

**Comment by StockiesLad** [comment]
It also doesn't carry mining levels either.

**Comment by lukebemish** [comment]
Well, I've got the tag stuff figured out at any rate. I'll go ahead and profile the modpack during startup tomorrow, and see if I can find what's slowing it down.

**Comment by lukebemish** [comment]
I think I've tracked down the performance stuff; I'll try to get a fix out tomorrow.

**Comment by lukebemish** [comment]
Should be fixed in the next update.

**Comment by StockiesLad** [comment]
Thank you for helping out! You're a legend!

**Comment by lukebemish** [comment]
New versions of DynAssetGen and EV are on modrinth, and should be on curseforge soon.
