### ISSUE TITLE
[BUG] Modded Ore variants not having mining levels

### ISSUE THREAD

**Issue by FluffyBumblee** [lukebemish/excavated_variants#41]
### What went wrong?

Vanilla ore variants for other rock types work but not modded ore variants.

Lukebemish I don't think fabric produces a debug.log because I saw some other one and It was only for forge.

### Platform

Fabric

### Version

0.4.2 and 0.5.5 tested

### Logs and Screenshots

[latest.log](https://github.com/lukebemish/excavated_variants/files/8678566/latest.log)

**Comment by lukebemish** [comment]
Looks like there may be issues for other mods too, so I'll leave this open till I can track everything down.

**Comment by lukebemish** [comment]
Okay, it works fine with just BYG and EV on their own, but doesn't work with EV in your modpack. I'm going to guess some mod has `replace: true` set in the tags for block levels or something; otherwise, I'm really not sure. Can you try without mythic metals, reset the caches, and try again?

**Comment by lukebemish** [comment]
Figured it out. The general issue is caused by how fabric datapacks work; for some unknown reason, they shove every mod datapack into a single conglomerate. I have no idea how tags even work inside of that; I'll look into what's necessary to get it working.
