### ISSUE TITLE
[BUG] MI textures not able to be found during block model generation

### ISSUE THREAD

**Issue by StockiesLad** [lukebemish/excavated_variants#44]
### What went wrong?

Some textures don't load. e.g. A ore wont have its texture so something like "Marble (ore_name)" will just have the marble texture

### Platform

Fabric

### Version

0.6.0

### Logs and Screenshots

[latest.log](https://github.com/lukebemish/excavated_variants/files/8693179/latest.log)

**Comment by StockiesLad** [comment]
I also saw this "backup" thing, it looked like a fail-safe. Is there a way to use that feature and manually add backups?

**Comment by lukebemish** [comment]
Do you have any custom configs? If so, what do they look like?

**Comment by lukebemish** [comment]
Also, could you stick logs in a gist in the future so they're readable on mobile?

**Comment by StockiesLad** [comment]
sure!

**Comment by StockiesLad** [comment]
> Do you have any custom configs? If so, what do they look like?

{
  "mod_id": "modern_industrialization",
  "provided_stones": [],
  "provided_ores": [
    {
      "id": "antimony_ore",
      "stone": [
        "stone",
        "deepslate"
      ],
      "block_id": [
        "modern_industrialization:antimony_ore",
        "modern_industrialization:deepslate_antimony_ore"
      ],
      "en_name": "Antimony Ore",
      "types": [
        "stone"
      ]
    }
  ]
}

**Comment by StockiesLad** [comment]
Other custom configs are working (besides enriched stones with weird names but that's trivial)

**Comment by StockiesLad** [comment]
here is a gist
https://gist.github.com/FluffyBumblee/3d6ddd42c3c0ffcaf2c0f03fa9544375

**Comment by lukebemish** [comment]
This is on Modern Industrialization's end. They put textures in `textures/blocks` instead of `textures/block`; the second one is the correct location.

**Comment by StockiesLad** [comment]
> This is on Modern Industrialization's end. They put textures in `textures/blocks` instead of `textures/block`; the second one is the correct location.

So could I make it myself and copy textures or is that stupid?

**Comment by lukebemish** [comment]
I'm not really sure what you mean. Honestly, it would work fine if there is either a blockstate file, model file, or texture file in an expected location. MI has none of the above.

**Comment by StockiesLad** [comment]
basically making a seperate textures/block with all the textures in it

**Comment by StockiesLad** [comment]
with all the required textures

**Comment by lukebemish** [comment]
You could, or just provide a block model or blockstate file, which would take up less space. Either way would work.

**Comment by StockiesLad** [comment]
How would I provide a block model directly

**Comment by lukebemish** [comment]
The same way you'd provide any other resource? With a resource pack or mod, most likely

**Comment by StockiesLad** [comment]
oh ok. Thank you for your help!
