### ISSUE TITLE
[BUG] Betternether ores not having drops when broken

### ISSUE THREAD

**Issue by StockiesLad** [lukebemish/excavated_variants#46]
### What went wrong?

Some Nether-specific ores dont have correlating drops

### Platform

Fabric

### Version

0.6.2

### Logs and Screenshots

https://gist.github.com/FluffyBumblee/b1ab2c5421ba7ad2c41a9169b09d1929

config
https://gist.github.com/FluffyBumblee/5a4e279cb5862c9e4e2a9453219b6491

**Comment by lukebemish** [comment]
Gonna need a lot more info than that. What ores? What drops?

**Comment by StockiesLad** [comment]
specifically the better nether ruby ores

**Comment by StockiesLad** [comment]
Better nether ores as a whole

**Comment by StockiesLad** [comment]
why didnt I fix the title lol

**Comment by StockiesLad** [comment]
I know what it is, betternether requires netherite for an item drop, imo this is very stupid bc a mining level would make more sense.

**Comment by StockiesLad** [comment]
Imma see if I can use KubeJS to fix this

**Comment by lukebemish** [comment]
It needing netherite _is_ how mining levels work

**Comment by lukebemish** [comment]
No, the real issue is that they have a custom loot table implementation for some reason, just like they did for block models. I'll fix it in an upcoming update.

**Comment by lukebemish** [comment]
Will be fixed on my end in the next release

**Comment by StockiesLad** [comment]
Oh ok, thanks!
