### ISSUE TITLE
Certain textures not loading

### ISSUE THREAD

**Issue by realpfred** [lukebemish/excavated_variants#47]
### What went wrong?

There are three specific textures of three different blocks that aren't loading properly. The blocks are the Andesite Copper Ore, Andesite Iron Ore, and the Andesite Coal Ore. However, every other ore block is perfectly fine. I noticed that this also happens in older versions of the mod as well.

### Platform

Forge

### Version

v1.18.2 (or Excavated Variants v0.6.2)

### Logs and Screenshots

![2022-05-19_22 58 39](https://user-images.githubusercontent.com/98147900/169441518-cf4f3dbc-b8ab-4450-b199-0a2654899202.png)
![2022-05-19_22 58 44](https://user-images.githubusercontent.com/98147900/169441522-e8519d8c-8aaf-4f00-be0a-c0a43f17eab9.png)
![2022-05-19_22 58 48](https://user-images.githubusercontent.com/98147900/169441534-a7bdeb77-9769-441e-864b-6f3916c45e81.png)

**Comment by lukebemish** [comment]
This is a known issue. You've got a resource pack with a lot of textures; turn up the texture count in the config for Excavated Variants.

**Comment by winnetrie83** [comment]
@lukebemish Can you give more specific information about wich file? There are 26 files in that folder
Everyone playing the modpack Better Minecraft Plus has this issue and wants to fix this.

**Comment by lukebemish** [comment]
The one with the relevant ores/stones; in this case, the one for vanilla Minecraft.

**Comment by winnetrie83** [comment]
thank you, found it and fixed it
