### ISSUE TITLE
[Enhancement] Discord and Auto Builds

### ISSUE THREAD

**Issue by StockiesLad** [lukebemish/excavated_variants#52]
### What feature would improve this mod?

Convenience of the mod devs sake as an easier means of communication.
Auto Builds similar to 'create-fabric' so people can get their hands on indev builds without pestering mod devs

### Why would this feature be useful?

Already explained...

### Is there any other relevant info about this feature request?

No.

### Mod Compatibility

- [X] This feature cannot be added through the config

**Comment by lukebemish** [comment]
Just clone the repo, and run `./gradlew build`, same as anything else. For discord, I can be pinged on the MMD discord, among others, but I will not be making a server specifically.

**Comment by StockiesLad** [comment]
It doesn't work unfortunately as the Dynamic Asset Generator dependency can't install.

**Comment by StockiesLad** [comment]
Any fix?

**Comment by lukebemish** [comment]
Publish it to a local maven

**Comment by StockiesLad** [comment]
How do you build everything if DAG isn't published

**Comment by StockiesLad** [comment]
I'm trying to setup a maven repo (im not a coder, atleast not yet) and it is difficult to get things working, especially since the latest DAG doesnt build.

**Comment by StockiesLad** [comment]
nvm, I used flatdir and it worked

**Comment by lukebemish** [comment]
...just publish DynAssetGen to your local maven. Clone the repo, run ./gradlew publish

**Comment by StockiesLad** [comment]
Dw I got it working now and I have the latest EV. Thanks for your help though so I know for next time.
