### ISSUE TITLE
[BUG] Issue with Andesit

### ISSUE THREAD

**Issue by ardissaps** [lukebemish/excavated_variants#55]
### What went wrong?

Andesit purpleblack.. First start aplication did not yet changed config. 

Only Andesite (Coal,Copper, Iron). all works fine

### Platform

Fabric

### Version

Latest

### Logs and Screenshots

https://imgur.com/a/wqMvRDy

**Comment by lukebemish** [comment]
I need your logs. Additionally, do you have any resource packs installed? Is caching on? Have you tried resetting the configs? Are you on latest 1.18.2 or the 1.19 alpha?

**Comment by ardissaps** [comment]
I am on 1.18.2, config deleted, didnt touch caching thing as this is my first install. 

Log after reloading same world :
https://paste.atlauncher.com/view/759bdd63-70a4-457e-b433-285661149ce1

Should I generate new world?

**Comment by lukebemish** [comment]
That shouldn't be needed. Once again, do you have any resource packs?

**Comment by ardissaps** [comment]
> That shouldn't be needed. Once again, do you have any resource packs?

Oh sorry, yes I do. Stay True.

**Comment by lukebemish** [comment]
Yes, this is a known issue. Turn up the `texture_count` value for andesite.

**Comment by ardissaps** [comment]
> Yes, this is a known issue. Turn up the `texture_count` value for andesite.

I don't understand :D 

In the resource pack directory or in EV config?

**Comment by lukebemish** [comment]
In the EV config

**Comment by ardissaps** [comment]
I only found these :
![cf](https://user-images.githubusercontent.com/82106625/173214070-db391cd7-07b4-4b75-a22f-93fa5389fd0c.jpg)

**Comment by lukebemish** [comment]
Please read the mod page, and the README.

**Comment by ardissaps** [comment]
I only found 3 word Andesite in minecraft.json in ev directory
![image](https://user-images.githubusercontent.com/82106625/173214237-440a68e5-274e-42de-b1e4-cc4f48371a5a.png)

**Comment by lukebemish** [comment]
Exactly. Add a higher `texture_count` to that entry

**Comment by ardissaps** [comment]
All of them? because there are many texture_count in the file, and also no texture_count word near Andesite word
.

**Comment by lukebemish** [comment]
No. *Add* a `texture_count` to the andesite entry, and make it larger than the default (which is either 5 or 10 in your version, I suspect).

**Comment by ardissaps** [comment]
Like this? look like default 5 on most entry
![image](https://user-images.githubusercontent.com/82106625/173214382-5435c80e-9c6e-4ed3-b411-60dd9ea8ea89.png)

**Comment by lukebemish** [comment]
Yes. If that doesn't work, try 15.

**Comment by ardissaps** [comment]
> Yes. If that doesn't work, try 15.

I just tested with 8 and it works! The default is 5 I guess? Thank you for your assistance sir, I'll take note if thing happen again. Great Mod! :)

**Comment by ardissaps** [comment]
> Yes. If that doesn't work, try 15.

I just tested with 8 and it works! The default is 5 I guess? Thank you for your assistance sir, I'll take note if thing happen again. Great Mod! :)

**Comment by ardissaps** [comment]
Look like the texture count must match with resource pack variant added. Last time I try the purple appear again in ratio of 1:8 (only andesite coal this time) then I look for Stay True zip file contain coal hve 7 variants and andesite is 8 so I changed according to them. Is that work that way? maybe can be added to the information. But anyway thank you so much for your time, I learned a lot.

**Comment by lukebemish** [comment]
The texture count needs to be at or larger than the number of textures the block could use.
