### ISSUE TITLE
[ENHANCEMENT] Ability to change Block Properties of Excavated Variants

### ISSUE THREAD

**Issue by onyxromero** [lukebemish/excavated_variants#58]
### What feature would improve this mod?

In the config, it would be nice to be able to set custom hardness values, resistances, etc.

### Why would this feature be useful?

This would allow harder materials to take longer to mine, for hardcore modpacks.

### Mod Compatibility

- [X] This feature cannot be added through the config

**Comment by lukebemish** [comment]
The hardness is already calculated from the hardness of the constituent blocks; I can probably add a config value for the ratio of this averaging pretty easily. More than that is likely outside the scope of this mod.

**Comment by onyxromero** [comment]
The only thing is, it takes no time to mine something if it's made out of bedrock with the default way it calculates.

**Comment by lukebemish** [comment]
Hmm. That looks like I'm not properly copying over the unbreakable status from the stone. Which makes sense wit the current setup. Should be an easy enough fix.

**Comment by onyxromero** [comment]
But before you fix that, can you at least add a hardness override? Cause in my pack I don't want bedrock ores to be completely unbreakable. That would defeat the purpose of bedrock variants.

**Comment by lukebemish** [comment]
Once again, this seems outside the scope of this mod; I do everything possible to avoid config bloat. I'll look at some possible options; I can probably find some way to put something for this together.

**Comment by onyxromero** [comment]
Thank you.

**Comment by lukebemish** [comment]
Do you want this ore to actually spawn in bedrock in the world?

**Comment by onyxromero** [comment]
Yep, which currently that works as intended.

**Comment by lukebemish** [comment]
I've put together a modifier system for ore variants for the next version; once I publish it, I'll dump a test config here to try for the bedrock stuff.

**Comment by onyxromero** [comment]
Again, thank you so much. This change is very much appreciated. The mod is absolutely brilliant.

**Comment by lukebemish** [comment]
On the newest version for 1.19 (0.7.3, once it ends up on curseforge), create a file in `globalresources/<any folder>/excavated_variants/<any namespace>/modifiers` named `<put some name here>.json`. In this file, put:
```json
{
  "filter": [
    "stone:<your stone name here>"
  ],
  "destroy_time": 10.0 //or whatever destroy time you want
}
```

Filling in all the details as necessary. Let me know if you have more questions.

**Comment by lukebemish** [comment]
There're also ways to filter by specific ores, or specific variants, or exclude specifi variants from the filter; I'll work on documenting it soon.
