### ISSUE TITLE
[BUG] Create Zinc Ore show Item ID instead of Name

### ISSUE THREAD

**Issue by ardissaps** [lukebemish/excavated_variants#65]
### What went wrong?

Only happen with Zinc Ore foll all stone. Configuration not yet edited (still default).

### Platform

Fabric

### Version

Latest

### Logs and Screenshots

![Screenshot 2022-06-18 132140](https://user-images.githubusercontent.com/82106625/174425688-fc491c74-e6c1-484d-92b5-cae38f3b16f7.jpg)

**Comment by ardissaps** [comment]
Asurine Stone
![image](https://user-images.githubusercontent.com/82106625/174426132-9ef17d62-82e8-4b9f-8d44-0161db7b7148.png)

**Comment by ardissaps** [comment]
Fixed sir, it was minecraft:smooth_basalt included on create.json files (by default), deleted the lines and it fixed! :p

**Comment by lukebemish** [comment]
That should not have caused this issue, meaning that something else is up here. Please include your full log, so that I can see the possible error/info messages that I log.

**Comment by lukebemish** [comment]
Issues of this sort should be fixed on the next 1.19 release.

**Comment by ardissaps** [comment]
> That should not have caused this issue, meaning that something else is up here. Please include your full log, so that I can see the possible error/info messages that I log.

I just figured out is is caused by dynamic asset generator cache, the problem when it happen once I installed unearthen, cleared the cache and working as normal rn.
Also known problem that I was just found is if we cache data and make install new mods without deleting cache can cause pickaxe not working.

**Comment by lukebemish** [comment]
Yes, of course; that's how a cache works. The solution is to delete your cache between changing mods, or disable caching.

**Comment by ardissaps** [comment]
> 

I see, now all work perfectly. thank you very much!
