### ISSUE TITLE
[BUG] [1.19] Pickaxe harvestability broken with Oh the Biomes You'll Go

### ISSUE THREAD

**Issue by Baggytrousers27** [lukebemish/excavated_variants#66]
### What went wrong?

Forge 41.0.45
dynamic_asset_generator-forge-1.19-0.6.4
excavated_variants-forge-1.19-0.6.3
TerraBlender-forge-1.19-2.0.0.113
Oh_The_Biomes_You'll_Go-forge-1.19-2.0.0.4

With Excavated Variants installed alongside Oh the Biomes You'll Go stone variants and ores are no longer harvestable with pickaxes.

### Platform

Forge

### Version

excavated_variants-forge-1.19-0.6.3

### Logs and Screenshots

[debug.log](https://github.com/lukebemish/excavated_variants/files/8948319/debug.log)
[latest.log](https://github.com/lukebemish/excavated_variants/files/8948320/latest.log)

With Excavated Variants (Jade used to show harvestability)
![2022-06-21_21 03 18](https://user-images.githubusercontent.com/15883796/174786328-14b10277-c04d-4960-9d03-205574a827b9.png)
![2022-06-21_21 09 09](https://user-images.githubusercontent.com/15883796/174786351-65fc6d87-0751-4e8f-98fc-1505eb465307.png)

Without Excavated Variants
![2022-06-21_21 06 02](https://user-images.githubusercontent.com/15883796/174786344-250faeb7-1517-47a0-8f4b-2475db8c0a7b.png)

**Comment by lukebemish** [comment]
Looks like there's some missing references, which is a bit curious. I'll have a look later today; do BYG ore variants show up fine?

**Comment by lukebemish** [comment]
Have you made any config changes?

**Comment by lukebemish** [comment]
(This will be fixed by default in the next update's default configs; to fix it in your existing configs, simply remove the lignite entry from the excavated_variants config for byg)

**Comment by lukebemish** [comment]
Not sure why it thinks the block is in those tags like 5 different times, or why it's not giving you a good error message, but ah well; I'll look at that another time.

**Comment by Baggytrousers27** [comment]
Groovy. Cheers and thanking you muchly.
