### ISSUE TITLE
[Question] My config

### ISSUE THREAD

**Issue by ardissaps** [lukebemish/excavated_variants#68]
### What went wrong?

Is there anything wrong with this config? 

### Platform

Fabric

### Version

Latest

### Logs and Screenshots

![image](https://user-images.githubusercontent.com/82106625/175760580-d92e123a-bc4b-4b8a-b981-f8efec6f2e4d.png)
![image](https://user-images.githubusercontent.com/82106625/175760612-e455ddfb-152e-47ad-a093-1d27577e9e06.png)

**Comment by lukebemish** [comment]
Looks good. What, exactly, is the issue?

**Comment by ardissaps** [comment]
> Looks good. What, exactly, is the issue?

The variant from [MineGate](https://modrinth.com/mod/minegate) is not appearing on search (they only add 2 ores), but others generated sucessfully. I was think there is typo or something. Is there a limit how many ore variant can be generated? (cached disabled)
![image](https://user-images.githubusercontent.com/82106625/175773813-ecde5cc6-7652-4026-9d27-046f0f94890b.png)

**Comment by ardissaps** [comment]
> Looks good. What, exactly, is the issue?

The variant from [MineGate](https://modrinth.com/mod/minegate) is not appearing on search (they only add 2 ores), but others generated sucessfully. I was think there is typo or something. Is there a limit how many ore variant can be generated? (cached disabled)
![image](https://user-images.githubusercontent.com/82106625/175773813-ecde5cc6-7652-4026-9d27-046f0f94890b.png)

**Comment by lukebemish** [comment]
No, there should be no limit. Can you try searching `@excavated tile` and see what comes up?

**Comment by lukebemish** [comment]
I found the issue. That mod's modid is `minegate-moreblocks`, even though they register under a different namespace. You can fix that pretty easily in your config. You should also file a bug report with them, though I'm not sure how much good it would do; their code is all messed up enough that it really just needs to be rewritten from scratch

**Comment by ardissaps** [comment]
Look like I am giving up their mod, as many duplicate item that already added by blockus, extended block shape etc (same exact model, ripped maybe? who know :D ). Make me a little bit sceptical about their mod (I like how they implement slab placement tho, but I'll look for alternative). Changing "minegate:obsidian_ore" to "minegate-moreblocks:obsidian_ore" does not seem to work. Thank you for the respond! I'll report again if I found something (running smooth this far).

**Comment by lukebemish** [comment]
Leave the block id as it was, change the mod id at the top
