### ISSUE TITLE
[ENHANCEMENT] Fabric Support Plan for 1.19

### ISSUE THREAD

**Issue by ardissaps** [lukebemish/excavated_variants#69]
### What feature would improve this mod?

Do you drop support for Fabric 1.19?

### Why would this feature be useful?

If yes I would move to Quilt starting from 1.19 as your mods is very necessary and can be reference to further looking for another mods that should be compatible with Quilt (because I was on quilt but many mods just don't like to run on that so on 1.18.2 i use fabric).

### Is there any other relevant info about this feature request?

Yes, to decide what loader should I use as base for my next modpack 1.19.

### Mod Compatibility

- [X] This feature cannot be added through the config

**Comment by lukebemish** [comment]
Fabric will not be supported going forward in 1.19+. Switch to Quilt instead; most fabric mods should continue to work fine on it for a good while to come.

**Comment by ardissaps** [comment]
I see, thank you for the respond! I guess moving to Quilt start from 1.19, I hope it went smooth.

**Comment by lukebemish** [comment]
Crazy smooth. Switching from fabric to quilt is insanely easy for mod authors. I actually managed to simplify some code by doing so.
