### ISSUE TITLE
[BUG] Crashes on game launch

### ISSUE THREAD

**Issue by NoShotz** [lukebemish/excavated_variants#70]
### What went wrong?

Game crashes when starting up

### Platform

Forge

### Version

0.7.0

### Logs and Screenshots

https://pastebin.com/raw/DzjuHNQ8

**Comment by lukebemish** [comment]
0.7.0 includes breaking config changes. Remove your configs

**Comment by NoShotz** [comment]
Well I've done that,  and the game boots, but I'm not seeing any of the variants in JEI. the creative menu, or in the world.

![image](https://user-images.githubusercontent.com/13302841/176096221-84e5d289-d2d1-49a3-ae40-7fa71ebbf681.png)
