### ISSUE TITLE
[BUG] No ores added to game

### ISSUE THREAD

**Issue by NoShotz** [lukebemish/excavated_variants#71]
### What went wrong?

When I went to check the creative inventory and JEI, none of the ores from this mod were listed in either of them, and I was not able to find any in the world.

![image](https://user-images.githubusercontent.com/13302841/176123240-7a3882a8-52c4-405b-a540-de83cfaba9ea.png)

One thing to note, the defaultresources folder that you mention on the mod description does not exist, only a globalresources folder which just contains `defaultresources_cache.json`

### Platform

Forge

### Version

0.7.0

**Comment by lukebemish** [comment]
defaultresources is for if you are doing a PR; you want globalresources. Still, it is strange that it would be empty. I will look into that today. What does the defaultresources cache look like?

**Comment by lukebemish** [comment]
Additionally, please provide a log. I log error information when possible

**Comment by lukebemish** [comment]
Fixed in 0.7.1
