### ISSUE TITLE
[BUG] Crash w/ REI

### ISSUE THREAD

**Issue by ghost** [lukebemish/excavated_variants#74]
### What went wrong?

REI integration breaks alongside this mod: `Caused by: java.lang.RuntimeException: Rerached side issue when loading REI plugin by Excavated Variants. Please use "rei_server", "rei_client" or "rei_common" instead.`

The crash log may state that the top-level issue is related to TerraBlender, however, removing this mod resolves all issues.

### Platform

Fabric

### Version

0.17.1-beta.4

### Logs and Screenshots

[latest.log](https://pastebin.com/0DZnZxz6)

**Comment by lukebemish** [comment]
Yeah, looks like REI made a breaking API change. I'll get to that in a bit. You can fix it temporarily by removing the REI entry from the quilt.mod.json entrypoint list

**Comment by ghost** [comment]
Heads up, here's a little implementation detail that might be useful for you: https://github.com/shedaniel/RoughlyEnoughItems/issues/951#issuecomment-1165927927

**Comment by lukebemish** [comment]
Yeah, that's what I figured. Need to look into any other 1.19 API changes with REI
