### ISSUE TITLE
[BUG] Crash w/ Blockus? Also Potentially Twigs?

### ISSUE THREAD

**Issue by ghost** [lukebemish/excavated_variants#75]
### What went wrong?

EV is potentially crashing with Blockus. It is also possible that a similar issue exists with [Twigs](https://modrinth.com/mod/twigs), as that mod shows up in the trace when it is enabled.

### Platform

Fabric

### Version

0.17.1-beta.4

### Logs and Screenshots

[latest.log](https://pastebin.com/Fjjvz70C)

**Comment by ghost** [comment]
Can confirm that removing only this mod resolves all problems.

**Comment by lukebemish** [comment]
This may have already been fixed; I need to check. If so, it will be in the next release
