### ISSUE TITLE
[BUG] Crash on startup (MC 1.18.2, forge 40.1.60)

### ISSUE THREAD

**Issue by MetaNade** [lukebemish/excavated_variants#78]
### What went wrong?

After applying the latest update of Excavated Variants (0.6.4) via Curseforge my profile crashes on startup. I have created a separate debug profile with the same minecraft/forge environment and only this mod (and dependency) installed and the crash persists.

### Platform

Forge

### Version

Minecraft v1.18.2, Forge v40.1.60, Excavated Variants v0.6.4.

### Logs and Screenshots

https://pastebin.com/raw/b0wr14nV

**Comment by lukebemish** [comment]
Forge messed up the mixin refmap again. I'll have it fixed shortly

**Comment by MetaNade** [comment]
Thank you for the swift reply! Glad to hear it is not a complicated issue.

**Comment by lukebemish** [comment]
Reuploaded a version with a working refmap; worked on my end, at any rate.
