### ISSUE TITLE
[ENHANCEMENT] More mod compatibility.

### ISSUE THREAD

**Issue by TheButterbrotMan** [lukebemish/excavated_variants#8]
https://www.curseforge.com/minecraft/mc-mods/pigsteel
https://www.curseforge.com/minecraft/mc-mods/gobber-fabric
https://www.curseforge.com/minecraft/mc-mods/enderite-mod-for-fabric
https://www.curseforge.com/minecraft/mc-mods/whimeraldmod
https://www.curseforge.com/minecraft/mc-mods/dirtmonds
https://www.curseforge.com/minecraft/mc-mods/alloygery
https://www.curseforge.com/minecraft/mc-mods/dense-ores-refabricated

I love your mod, its awesome. Its the best Orevariant mod i ever seen.

**Comment by TheButterbrotMan** [comment]
https://www.curseforge.com/minecraft/mc-mods/croparia

Compatibility for Elematilius Ore :)

**Comment by Sunconure11** [comment]
https://www.curseforge.com/minecraft/mc-mods/blockus

**Comment by lukebemish** [comment]
There should already be Blockus compat

**Comment by Sunconure11** [comment]
https://www.curseforge.com/minecraft/mc-mods/dinocraft-dctm

**Comment by Sunconure11** [comment]
https://www.curseforge.com/minecraft/mc-mods/sulfur-and-potassium-make-more-gunpowder

**Comment by TheButterbrotMan** [comment]
https://www.curseforge.com/minecraft/mc-mods/ore-revolution#c90

**Comment by Sunconure11** [comment]
https://www.curseforge.com/minecraft/mc-mods/magnificent-malachite

**Comment by lukebemish** [comment]
A blanket statement being placed on all default config requests: I may or may not get around to adding any of these to the default configs. If *you* would like to, or have already, written configs for this mod/mods, feel free to open a pull request to add these configs. They should be placed under `common/src/main/resource/default_configs`. For the config format, see the CurseForge page.

**Comment by lukebemish** [comment]
I am going to close this and all similar issues; if you would like, please open a pull request with a default config for the relevant mod.
