### ISSUE TITLE
[BUG] Crashing on Quilt

### ISSUE THREAD

**Issue by Sunconure11** [lukebemish/excavated_variants#81]
### What went wrong?

Trying to boot up the game results in this crash. Not much more to say.

### Platform

Fabric

### Version

0.8.0

### Logs and Screenshots

https://pastebin.com/9yGm179r

**Comment by lukebemish** [comment]
Quilt's having trouble reading a JiJed dependency. I'll look into it.

**Comment by lukebemish** [comment]
Fixed in 0.8.1
