### ISSUE TITLE
[BUG] Server Client async

### ISSUE THREAD

**Issue by BrekiTomasson** [lukebemish/excavated_variants#82]
### What went wrong?

Just updated to 0.6.4 on both the server and client and am having a weird issue where the client is reporting that it cannot detect a number of blocks from this mod that the server is reporting. I did not have this issue in 0.6.2, and have also tried creating a brand new world on the server using 0.6.4 to see if that would help.

### Platform

Fabric

### Version

0.6.4

### Logs and Screenshots

![telegram-cloud-photo-size-4-5969838872122734396-y](https://user-images.githubusercontent.com/7026735/180480245-e873a1c2-b1cb-4937-9fc0-dc8098754dea.jpg)

**Comment by lukebemish** [comment]
Delete your configs on both server and client

**Comment by BrekiTomasson** [comment]
Thanks for the tip, lemme try that and get back to you.

**Comment by BrekiTomasson** [comment]
Yup, that seems to have done it.  Shame it couldn't figure this out on its own, but glad that it's working anyway ;) 

Thanks!

**Comment by lukebemish** [comment]
It will never be able to figure stuff like this out on its own; you had different configs on the server and client. Probably because you'd cleared the configs of one after updating, but not the other
