### ISSUE TITLE
[ENHANCEMENT] Suggestion...

### ISSUE THREAD

**Issue by HexBugOrion** [lukebemish/excavated_variants#83]
### What feature would improve this mod?

Fabric support for 1.19

### Why would this feature be useful?

This would be very useful for people who don't/can't use Quilt (I'm running a modpack that has mods that break on Quilt like Modern Industrialization and such)

### Mod Compatibility

- [X] This feature cannot be added through the config

**Comment by lukebemish** [comment]
I will not be supporting Fabric going forward. If you want to use this mod with mods that do not work on Quilt, talk to those mods' authors instead for a Quilt port.
