### ISSUE TITLE
[BUG] [1.18.2] Crash on startup

### ISSUE THREAD

**Issue by GeorgeOrwell1** [lukebemish/excavated_variants#84]
### What went wrong?

The game crashed on startup while having your mod installed which doesn't happen when your mod isn't installed. This also happens when I only have the dependency mod and Excavated Variants installed. This isn't due to something in my JVM configuration as it works well with the other mods I have installed (see third figure).

### Platform

Forge

### Version

Excavated Variants: v0.5.5
Dynamic Asset generator: v.0.6.3
Forge: 40.1.68

### Logs and Screenshots

![bild](https://user-images.githubusercontent.com/72312697/181828769-f878f215-0de9-4a45-b36a-3b41cebbc5ca.png)
_Game crash with exit code: 1_
![bild](https://user-images.githubusercontent.com/72312697/181828994-855ae3a8-2312-4e37-bc39-dbe7a51fe395.png)
[latest.log](https://github.com/lukebemish/excavated_variants/files/9222723/latest.log)
![bild](https://user-images.githubusercontent.com/72312697/181830281-ccf24d0f-f4de-4c0c-9e5e-12245960372e.png)
_Picture which shows Minecraft + Forge running fine **WITHOUT** the Excavated Variants mod._

**Comment by lukebemish** [comment]
v0.5.5 is *extremely* old. Please try again on a newer version.
