### ISSUE TITLE
Certus Quartz Ore + Andesite = Missing Texture

### ISSUE THREAD

**Issue by BrekiTomasson** [lukebemish/excavated_variants#85]
### What went wrong?

Not sure if I'm doing something wrong on my end or if there's any way to force the mod to regenerate textures, but for some reason, Certus Quartz Ore (from `appliedenergistics2`) is ending up with a missing texture when this mod tries to generate the Andesite version. It works fine with other stone block types by the looks of it, so it doesn't seem to be a general problem with that particular ore.

### Platform

Fabric

### Version

1.18.2-0.6.4

**Comment by lukebemish** [comment]
https://github.com/lukebemish/excavated_variants/issues/55

**Comment by lukebemish** [comment]
(at least, assuming you have a resource pack. If this is not with a resource pack, please provide a log, and screenshots)
