### ISSUE TITLE
"Whitelisting" stones

### ISSUE THREAD

**Issue by BrekiTomasson** [lukebemish/excavated_variants#86]
### What feature would improve this mod?

While I'm really impressed with how many ores from other mods this mod has support for, I feel that there are a couple of stone types from other mods that are not included in the mix when generating variants. And I understand that it's out of scope for this mod to have all of them, so why not add a `whitelist_stones` field to the configuration file, where you can add the block id of the stone type in question and it tries to include it in the mix when generating ore variants?

### Why would this feature be useful?

While ore distribution is very consistent across the world, sometimes you hit upon a patch of rocks that were added by another mod where the ore distribution suddenly drops dramatically.

### Mod Compatibility

- [X] This feature cannot be added through the config

**Comment by BrekiTomasson** [comment]
(I apologize in advance if this can be done using the config files somehow, I am still not 100% sure about how to handle the files in the `/config/excavated_variants` folder, if you can create new ones that the mod automatically picks up on, etc.)

**Comment by lukebemish** [comment]
This is the whole purpose of the config files. Their structure is described in the README and on the mod page.
