### ISSUE TITLE
Idea regarding `techreborn`Ores

### ISSUE THREAD

**Issue by BrekiTomasson** [lukebemish/excavated_variants#87]
### What feature would improve this mod?

Most ores in the game drop the ore when breaking the block, so it doesn't matter if you're mining an Andesite Copper Ore Block or a Granite Copper Ore Block, the item you end up with is still going to be the Raw Copper. But since `techreborn` ores often require grinding in order to get the output, you very quickly end up with an inventory full of Granite Galina Ore, Andesite Galina Ore, Carbonite Galina Ore, Diorite Galina Ore, etc, etc, etc. 

Feature request is basically this: Would it be possible to have a configurable toggle for individual ores that makes it so that they always drop their "normal" counterpart? So that no matter if I'm breaking a Carbonite Galina Ore or a Granite Galina Ore, it still drops a `techreborn:galena_ore` block rather than the `excavated_variants` version?

### Why would this feature be useful?

While it *does* break immersion slightly, it would make inventory management a whole lot easier, and you wouldn't end up with those three Granite Bauxite Ore blocks in your inventory that you just didn't notice when shuffling ores into your grinder setup. :)

### Is there any other relevant info about this feature request?

When this is toggled for any given block, the mod would need to take into account that Silk Touch:ing a block always drops the `excavated_variants` version of the block rather than the "original" block.

### Mod Compatibility

- [X] This feature cannot be added through the config

**Comment by lukebemish** [comment]
This is what the `unobtainable_variants` config entry is for. This is described both on the mod page and the README.

**Comment by BrekiTomasson** [comment]
No, that's not entirely true.

> unobtainable_variants: If this is set to true, variants will drop the base ore, even with silk touch.

My suggestion was to be able to implement this on a per-ore basis and **not** modify the Silk Touch behavior.

**Comment by lukebemish** [comment]
Ah. So, to confirm what you are saying, you would want an option so that silk touch causes the variant block to drop and non-silk-touch causes the original block to drop?

**Comment by lukebemish** [comment]
This would be... A bit ugly to implement, perhaps, if I did it through a config option. I could probably add this through the modifiers system with relative ease, though. I'll look at it

**Comment by BrekiTomasson** [comment]
Right - and I want to be able to do so on a per-ore basis, not on a global `unobtainable_variants` level. I suggest an optional config option in the per-mod config files; something like:

```
    {
      "block_id": [
        "techreborn:galena_ore",
        "techreborn:deepslate_galena_ore"
      ],
      "en_name": "Galena Ore",
      "types": [
        "stone"
      ],
      "id": "galena_ore",
      "drops_variants": false, // <--- this row here.
      "stone": [
        "stone",
        "deepslate"
      ]
    },


```

**Comment by lukebemish** [comment]
No, this will not be a variant config option. It will use the modifier system.

**Comment by BrekiTomasson** [comment]
Whichever way works best for you. :)

**Comment by lukebemish** [comment]
Will be implemented in next release; closed by commit.
