### ISSUE TITLE
[BUG] Game not launching with mod installed.

### ISSUE THREAD

**Issue by murao-kun** [lukebemish/excavated_variants#88]
### What went wrong?

Game stopping from launching, when I install mod in my modpack.

### Platform

Forge

### Version

Minecraft 1.19.1, Forge 42.0.9 and both of your mods 1.0.0

### Logs and Screenshots

[latest.log](https://github.com/lukebemish/excavated_variants/files/9274682/latest.log)
[debug.log](https://github.com/lukebemish/excavated_variants/files/9274683/debug.log)

**Comment by lukebemish** [comment]
I'm not seeing a crash in either of those. Is it actually crashing, or stopped from launching another way? Either way, can you either provide a launcher log, assuming the crash is somehow not logged, and/or try with just Excavated Variants and DynAssetGen on the same Minecraft/forge versions?

**Comment by murao-kun** [comment]
Seems like I got the wrong version of the mod, now it is booting normally and fine. So I should close it.
