### ISSUE TITLE
[BUG] 1.19.2 Forge broke something again.

### ISSUE THREAD

**Issue by Baggytrousers27** [lukebemish/excavated_variants#89]
### What went wrong?

Forge 1.19.2 43.1.2
dynamic_asset_generator-forge-1.19.2-1.0.1
excavated_variants-forge-1.19.2-1.0.1

java.lang.NoSuchFieldError: RECIPE_SERIALIZER_REGISTRY

java.lang.reflect.InvocationTargetException

### Platform

Forge

### Version

excavated_variants-forge-1.19.2-1.0.1

### Logs and Screenshots

[crashlog](https://github.com/lukebemish/excavated_variants/files/9391300/crash-2022-08-22_14.47.57-fml.txt)
[debug.log](https://github.com/lukebemish/excavated_variants/files/9391306/debug.log)

**Comment by lukebemish** [comment]
Looks like JiJ didn't let me reobjuscate my final jar. No idea in heck why it keeps doing that; Forge's system is just broken. I'll try to get a patch out.

**Comment by Baggytrousers27** [comment]
The forge hydra; fix one thing 5 more issues arise in its place.

**Comment by lukebemish** [comment]
Should be fixed in 1.0.2, which is on modrinth and will be on CF soon. Rather annoyed with jarJar right now, but whatever.
