### ISSUE TITLE
[ENHANCEMENT] Bewitchment cross-compat

### ISSUE THREAD

**Issue by Sunconure11** [lukebemish/excavated_variants#9]
BW adds salt and silver ores. It might be worthwhile to add compat for them.

**Comment by lukebemish** [comment]
Probably pretty easy unless they do weird stuff. Should be added in the next update or so.

**Comment by lukebemish** [comment]
A blanket statement being placed on all default config requests: I may or may not get around to adding any of these to the default configs. If *you* would like to, or have already, written configs for this mod/mods, feel free to open a pull request to add these configs. They should be placed under `common/src/main/resource/default_configs`. For the config format, see the CurseForge page.

**Comment by lukebemish** [comment]
I am going to close this and all similar issues; if you would like, please open a pull request with a default config for the relevant mod.
