### ISSUE TITLE
[BUG] (BetterEnd) Thallasium and Amber ore variants broken

### ISSUE THREAD

**Issue by RyanIsAinmDom** [lukebemish/excavated_variants#90]
### What went wrong?

All of the variants of Amber and Thallasium seem to be broken.
Using the latest Quilt 1.19.2 build, and have tried deleting my config.
![BrokenVariants](https://user-images.githubusercontent.com/96996608/186018784-119199fe-ae8d-4dce-980f-205edbbdf3ca.png)

### Platform

Quilt

### Version

1.0.1

**Comment by lukebemish** [comment]
Please include your logs

**Comment by RyanIsAinmDom** [comment]
[latest.log](https://github.com/lukebemish/excavated_variants/files/9397649/latest.log)

Sorry about that

**Comment by lukebemish** [comment]
Ah heck, it's this problem again. Better End does some annoying stuff with their asset generation that is generally problematic for anyone else wanting to access their resources. I'll get a workaround of some sort out shortly

**Comment by lukebemish** [comment]
Should be fixed in 1.0.3
