### ISSUE TITLE
[BUG] Loading stops

### ISSUE THREAD

**Issue by KyrDerz** [lukebemish/excavated_variants#92]
### What went wrong?

This was the latest mod I've installed. For some reason, every time I start the game, it just never loads past:
[Worker-Main-19/INFO]: [OptiFine] BetterGrass: Parsing default configuration optifine/bettergrass.properties

It just stays there to infinity.

### Platform

Forge

### Version

0.6.4

### Logs and Screenshots

[2022-08-30-1.log](https://github.com/lukebemish/excavated_variants/files/9448837/2022-08-30-1.log)

**Comment by lukebemish** [comment]
Please try without Optifine and provide a new log.

**Comment by KyrDerz** [comment]
I know I may have one or two mods extra...

[latest.log](https://github.com/lukebemish/excavated_variants/files/9448955/latest.log)

**Comment by lukebemish** [comment]
Alright, I'm not seeing an actual crash here. Does it actually crash, or just freeze? If it just freezes, it could be you've just got an absolute ton of mods. Try letting that sit for 15 minutes or so. If that's not doing anything, or if it's actually crashing, please try and provide a launcher log. If it freezes, are you manually stopping the program? Additionally, are you using a publically available modpack that I could test this on locally?

Unless this turns out to be an extremely major issue, I likely won't be touching it since 1.18.2 is out of support.

**Comment by KyrDerz** [comment]
It freezes, I mean, it doesn't crash or freeze the window. It just stops loading and sits eating ram.
I do have way too many mods. Everything is updated at the moment. I can provide an archive with all the mods and configs. It's pretty much drag and drop on a clean 1.18.2 version.

I've sat on it for at least 45 min last time. It only acts like this with excavated variants and its API. I've thrown 10gb ram, no changes.

**Comment by lukebemish** [comment]
Alright. It looks like some other mod is likely doing something funky during the resource loading process that causes DynAssetGen to throw a fit; without an easy way to test, I couldn't tell you which. I'd recommend doing a binary search and seeing if you can find which other mod is involved, which may give me more options.

**Comment by KyrDerz** [comment]
I don't really know how to do that tbh. I just excavated_variants and the API, so that fixed it.

**Comment by lukebemish** [comment]
Basically, try removing half of your mods, except EV; if the problem goes away, then the mod that's got some weird interaction is in that half. Either way, continue with half of the half that had the issue, and so on, until you can isolate the other mod involved

**Comment by TheRTGGaming** [comment]
The problem is with Optifine. I have had no problems with 112 mods. once i put optifine on the mod pack the loading stops. meaing there is a problem between this mod and optifine. glad i can help :D

**Comment by lukebemish** [comment]
Optifine breaks DynAssetGen; that is a known issue. There is nothing I can do to solve it either, as Optifine makes some bad assumptions about what mods do that aren't necessarily true.

**Comment by lukebemish** [comment]
However, this will be left open as a log without Optifine has been provided.

**Comment by TheRTGGaming** [comment]
or leave a comment "Does not work with Optifine: working on issue" untill you can find a work around

**Comment by lukebemish** [comment]
I'll reiterate. The bug reported here has nothing to do with Optifine

**Comment by TheRTGGaming** [comment]
yes. Optifine, does not work with your mod meaning that yes this has to do with Optifine and your mod not working with each other. meaning that when the loading freezes meaning that Optifine and your mod had a corruption when loading minecraft

**Comment by lukebemish** [comment]
...no. The bug reported here has nothing to do with Optifine, as a log *without* Optifine that still has the bug was provided.

**Comment by lukebemish** [comment]
Some stuff you could try to troubleshoot the bug reported in this report: try deleting and regenerating all your configs.

**Comment by lukebemish** [comment]
Closing this due to lack of response; feel free to add more information, and I'll open it up again.
