### ISSUE TITLE
[ENHANCEMENT] 3D ores resourcepack compatibility

### ISSUE THREAD

**Issue by deadspidervenom** [lukebemish/excavated_variants#93]
### What feature would improve this mod?

Allowing people to use said resource pack to view all the ores in 3d

### Why would this feature be useful?

Because currently when installed the block textures in game break

### Is there any other relevant info about this feature request?

this error appears for each ore. picture of what the ores look like ( that is not a copper block its a ore block)
[17:07:59] [Worker-Main-7/ERROR]: Using missing texture, unable to load excavated_variants:textures/block/andesite_copper_ore626.png : java.io.FileNotFoundException: excavated_variants:textures/block/andesite_copper_ore626.png

![image](https://user-images.githubusercontent.com/12871122/189461046-c35e0dde-68eb-4de7-a79e-aaa05f6263a4.png)

### Mod Compatibility

- [X] This feature cannot be added through the config

**Comment by lukebemish** [comment]
Can you provide a full log trying to load the game with the resource pack present?

**Comment by deadspidervenom** [comment]
[latest.log](https://github.com/lukebemish/excavated_variants/files/9539438/latest.log)

**Comment by lukebemish** [comment]
Can you try this again on 1.19? The system changed substantially from 1.18.2 to 1.19, in a way that hopefully makes it far more flexible. It's a system that would be very time consuming to backport to 1.18.2, which is no longer in development.

**Comment by deadspidervenom** [comment]
playing a modpack so kinda can't update too 1.19. I mean technically speaking i could try. however it would be very time consuming to port a entire modpack thats not mine too 1.19. More so if multiple mods are no longer in development, had updates that break other mods, or had enough changes that updates breaks the pack.

**Comment by lukebemish** [comment]
Unfortunately, unless you can give me more information about if/how this issue occurs in 1.19.2, there is nothing I can do about it. No active development is being done on 1.18.2. Closing this for now; I'll reopen if information from 1.19 is provided
