### ISSUE TITLE
[BUG] priority config does not work (also, better nether's lapis should be separate from vanilla)

### ISSUE THREAD

**Issue by qtow** [lukebemish/excavated_variants#97]
### What went wrong?

The logic at [ConfigResource.java:30](https://github.com/lukebemish/excavated_variants/blob/b3e2f17489a6695e21224058d3a922fee5726171/Common/src/main/java/io/github/lukebemish/excavated_variants/data/ConfigResource.java#L30) is backwards - you want `filter` to keep things _not_ contained in the original list. You might also consider using [Stream#concat](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/util/stream/Stream.html#concat(java.util.stream.Stream,java.util.stream.Stream)) and [Stream#disjoint](https://docs.oracle.com/en/java/javase/18/docs/api/java.base/java/util/stream/Stream.html#distinct()), a bit overkill but perhaps more expressive.

I found this because BetterNether's lapis ore is becoming the "default" lapis ore, which makes all of the non-vanilla variants drop BetterNether's Lapis Pile's, and also require a diamond pickaxe to mine. I think that BetterNether's lapis should probably be a distinct ore from vanilla lapis, just like vanilla nether gold is distinct from overworld gold.

Also, they should all be called Lapis Lazuli Ore, not Lapis Ore.

### Platform

Quilt

### Version

1.0.3

**Comment by lukebemish** [comment]
I'll fix that in the next release; lapis ore is named that way since the names get really large with stone names otherwise.

**Comment by qtow** [comment]
Should the list on [ExcavatedVariants:128](https://github.com/lukebemish/excavated_variants/blob/b3e2f17489a6695e21224058d3a922fee5726171/Common/src/main/java/io/github/lukebemish/excavated_variants/ExcavatedVariants.java#L128) contain lapis as well?

**Comment by lukebemish** [comment]
Fixed in recent commits; fix will be included in the next version

**Comment by lukebemish** [comment]
Fixed in upcoming 1.19.3 release; waiting on https://github.com/MinecraftForge/MinecraftForge/issues/9208
