### ISSUE TITLE
[BUG] Issue with Chinese

### ISSUE THREAD

**Issue by nageih** [lukebemish/excavated_variants#98]
### What went wrong?

When I made the configuration file, I found that when en_name is Chinese, it can only recognize four characters normally, as shown in the figure, if more or less than four characters, it will display garbled characters

### Platform

Forge

### Version

v0.6.4

### Logs and Screenshots

![~{K BECI0B 11NF57J}9Z6J](https://user-images.githubusercontent.com/102042030/194787194-c0b0d7f1-2d46-4cc0-a405-52dade1a7642.jpg)
![@7PK8H`0EW$DQ585GM6AT~O](https://user-images.githubusercontent.com/102042030/194787195-5f3d4921-97c6-486f-8883-d08f175e6552.jpg)

**Comment by lukebemish** [comment]
I have a couple of ideas what might cause that, but the 1.18 version is no longer being developed; if you can reproduce this in 1.19 and give me a log, as well as your configs, I can probably try to fix it.

**Comment by nageih** [comment]
So far, I only found this problem in 1.18, which is my configuration
[minecraft.txt](https://github.com/lukebemish/excavated_variants/files/9743244/minecraft.txt)
[quark.txt](https://github.com/lukebemish/excavated_variants/files/9743245/quark.txt)

**Comment by lukebemish** [comment]
Once again, the 1.18 version is no longer being developed. If the same issue exists in 1.19, please provide a full log and you configuration files for 1.19

**Comment by lukebemish** [comment]
If I had to guess, this issue may occur if certain characters need to be escaped in JSON files. However, I'm unable to tell without a config and logs; please provide them *for 1.19*; I'm going to close the issue for now, but comment with those and I'll re-open it.
