### ISSUE TITLE
[BUG] Nether Gold + Quartz Smooth basalt variations have "create" in their ids

### ISSUE THREAD

**Issue by Synthestra** [lukebemish/excavated_variants#99]
### What went wrong?

With both Smooth Quartz and nether gold ore/quartz both being vanilla blocks, it makes no sense that the id would be "excavated_variants:create_smooth_basalt_nether_gold_ore" for example.

This, of course, also would have the Create mod installed

### Platform

Forge

### Version

1.18.2-0.6.4

### Logs and Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/22637135/194883968-ff6d43a5-ca94-41bb-8454-a29ead5de37b.png)
![Screenshot_3](https://user-images.githubusercontent.com/22637135/194885062-dbc340d4-c942-4b79-8c7d-d6d18c0634a9.png)
the nether variants have "create" while the diamond one below does not
![Screenshot_2](https://user-images.githubusercontent.com/22637135/194885145-cda7cae3-9c91-419f-b953-9338729d291e.png)

**Comment by lukebemish** [comment]
Nether smooth basalt and overworld smooth basalt are different variants. This is intentional.

**Comment by Synthestra** [comment]
Regardless of Create generating smooth basalt in the nether, both the blocks used to generate the ore are vanilla

**Comment by lukebemish** [comment]
Yes; that's irrelevant. The stone object created by Excavated Variants is only present if create it. Vanilla and create smooth stone ore variants use different stone objects
